### ISSUE TITLE
镜像里面找不到nvidia-smi

### ISSUE THREAD

**Issue by leizhu1989** [Tongjilibo/bert4torch#101]
大佬，您好，请问您提供的镜像里面没法使用nvidia-smi，请问镜像里没有显卡驱动吗

**Comment by Tongjilibo** [comment]
我晚上看下

**Comment by Tongjilibo** [comment]
你是用的下面的镜像吗？我这边是可以的啊
```shell
docker pull tongjilibo/tensorrt:11.3.0-cudnn8-devel-ubuntu20.04-tensorrt8.4.1.5

docker run -it --name trt_torch --gpus all -v /home/libo/tensorrt:/tensorrt tongjilibo/tensorrt:11.3.0-cudnn8-devel-ubuntu20.04-tensorrt8.4.1.5 /bin/bash
```
![image](https://user-images.githubusercontent.com/33407736/223754488-4eb82d66-86a9-4867-b93a-a8495f988b71.png)

**Comment by leizhu1989** [comment]
对的啊，就是这个镜像，我的本地系统是ubuntu18.04的，有点奇怪；我在本地搭建了环境，跑通了您md文档里的demo

**Comment by leizhu1989** [comment]
nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.

**Comment by leizhu1989** [comment]
在镜像里find是有的啊
find / -name libnvidia-ml.so
/usr/local/cuda-11.3/targets/x86_64-linux/lib/stubs/libnvidia-ml.so

我本地的cuda是11.0版本

**Comment by Tongjilibo** [comment]
我本地cuda版本是11.3，供参考，至于环境问题我这边也不是很方便调试，只能保证自己提供的镜像在适配的环境中可以正常执行
