### ISSUE TITLE
有关模型微调

### ISSUE THREAD

**Issue by leizhu1989** [Tongjilibo/bert4torch#108]
大佬，您好！
我目前有少量的数据，一千来条数据(句子 id)。想微调下模型，请问这可以吗？需要冻结一些参数训练吧，怕数据太少过拟合，如果可以的话，要怎么做呢

**Comment by Tongjilibo** [comment]
您好，微调是可以的，冻结参数是一种选择，您是做什么任务呢？建议可以配合一些数据增广手段，或者有一些半监督方式也可以看看

**Comment by leizhu1989** [comment]
想做多分类任务，数据形式：（句子 id），id是标签，和task_sentiment_classification_albert数据标注一样，他那个是情感二分类，我这个有多类，后面也许有上百类，每一类有一些类似的句子描述语料。请问数据太少的话，可以直接微调，还是需要冻结参数训练啊，冻结参数要怎么操作下呢？求大佬指点

**Comment by leizhu1989** [comment]
我也想过像做二分类，0,1是不是属于同一类这样。这样组合的数据就多些了，这样要提取句向量来计算相似度。多分类可以直接用分类的结果，也可以用softmax之前的向量计算相似度吧

**Comment by skykiseki** [comment]
> 想做多分类任务，数据形式：（句子 id），id是标签，和task_sentiment_classification_albert数据标注一样，他那个是情感二分类，我这个有多类，后面也许有上百类，每一类有一些类似的句子描述语料。请问数据太少的话，可以直接微调，还是需要冻结参数训练啊，冻结参数要怎么操作下呢？求大佬指点

交叉熵一样可以用在多分类的，直接跑就可以了，label: 0,1,2,3,4这样

**Comment by Tongjilibo** [comment]
感觉可以直接多标签先试试看，一般可以直接用BceWithLogitLoss或者可以看看苏神的[多标签版本交叉熵](https://spaces.ac.cn/archives/7359)

**Comment by leizhu1989** [comment]
@skykiseki 嗯，我发现整理几天才500来条数据，写的都要吐了。500条多分类有些少啊，我把它们组合成二分类，12万多条数据先试试看，多分类感觉一步到位了

**Comment by leizhu1989** [comment]
@Tongjilibo 好的
