### ISSUE TITLE
权重转换问题

### ISSUE THREAD

**Issue by Clearloveplus7** [Tongjilibo/bert4torch#112]
提问时请尽可能提供如下信息：

权重转换我看这里的说到使用第三种方法，具体如何转换呢这个torrent

**Comment by Tongjilibo** [comment]
[torrent](https://pan.baidu.com/s/1yBaYZK5LHIbJyCCbtFLW3A?pwd=phhd)我有放百度云，转换脚本是[脚本](https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/convert_llama_facebook.py)
