### ISSUE TITLE
有关提取token向量的探讨

### ISSUE THREAD

**Issue by leizhu1989** [Tongjilibo/bert4torch#116]
大佬，您好，请问这个函数里面cls这个地方hidden_state[:, 0]是指取最后一个隐藏层，第一个token的向量吗；如果是的话，为啥要取开头的啊，而不是结尾的向量呢

def get_pool_emb(hidden_state=None, pooler=None, attention_mask=None, pool_strategy='cls', custom_layer=None):
    ''' 获取句向量

    :param hidden_state: torch.Tensor/List(torch.Tensor)，last_hidden_state/all_encoded_layers
    :param pooler: torch.Tensor, bert的pool_output输出
    :param attention_mask: torch.Tensor
    :param pool_strategy: str, ('cls', 'last-avg', 'mean', 'last-max', 'max', 'first-last-avg', 'custom')
    :param custom_layer: int/List[int]，指定对某几层做average pooling
    '''
    if pool_strategy == 'pooler':
        return pooler
    elif pool_strategy == 'cls':
        if isinstance(hidden_state, (list, tuple)):
            hidden_state = hidden_state[-1]
        assert isinstance(hidden_state, torch.Tensor), f'{pool_strategy} strategy request tensor hidden_state'
        return hidden_state[:, 0]

**Comment by skykiseki** [comment]
这里取的就是首位也就是[CLS]的向量作为整个句子的表征

**Comment by Tongjilibo** [comment]
理论取结尾也不是完全不可行，举例你可以样本最后加个特殊token，finetune时候用这个token的向量去接下一步的任务，可以实验下看看效果，xlnet好像就是最后一位是<cls>，padding在前面，取最后一位的向量去做下游分类任务

**Comment by leizhu1989** [comment]
@Tongjilibo 好的，谢谢大佬回答。发现我的数据很容易过拟合，感觉还是句子太简单，数量太少了。大佬有扩增数据方法推荐的吗

**Comment by leizhu1989** [comment]
@skykiseki 感谢大佬提点

**Comment by skykiseki** [comment]
> @Tongjilibo 好的，谢谢大佬回答。发现我的数据很容易过拟合，感觉还是句子太简单，数量太少了。大佬有扩增数据方法推荐的吗

直接用roformer-sim(simbert-v2)，examples里面就有

**Comment by leizhu1989** [comment]
@skykiseki 谢谢大佬提点，我用pooler的token和hidden_state[:, 0]对比，效果差异不大；我是多分类十几个类，发现用多分类交叉熵提取的句向量计算相似度要比我把多类拆分成二分类(相同，不相同)对计算类似句子的区分度要好些。可是像有些句子只有一两个字不同就意思不同的，用句子相似度计算相似度很高。想通过相似度计算两个句子相似程度，但对那种一两个字不同意思不同的很难处理，多分类提取的句向量还好点。embedding训练的对这样的适应性很差啊，相似度都非常高。不知道是不是我哪里不对
