### ISSUE TITLE
DP模式gradient_penalty下Loss起步无限大

### ISSUE THREAD

**Issue by skykiseki** [Tongjilibo/bert4torch#120]
提问时请尽可能提供如下信息：

基本信息
你使用的操作系统: ubuntu20.04
你使用的Python版本: 3.8.10
你使用的Pytorch版本: 1.10.2
你使用的bert4torch版本: 0.2.7.post2
你加载的预训练模型: bert-base

核心代码
adversarial_train = AdversarialTraining('gradient_penalty')

model = BaseModelDP(model)

#任务是个[CLS]text1[SEP]text2[SEP]判断text1,text2是否相似的二分类下游问题

### 输出信息
```shell
# loss起步极大近10亿，单卡无问题。
```

**Comment by Tongjilibo** [comment]
是的，目前是有这个问题，因为DP和DDP都是在把model外面包了一层，因此对抗训练内部的解析可能存在问题，我看下修复一下

**Comment by Tongjilibo** [comment]
是不是只有gradient_penalty有问题，其他对抗训练模块有问题吗？

**Comment by skykiseki** [comment]
> 是不是只有gradient_penalty有问题，其他对抗训练模块有问题吗？

其他无，叫了个人都测了一遍今天hhhh
