### ISSUE TITLE
量化后的模型可以保存并 重新加载使用吗？

### ISSUE THREAD

**Issue by a2012456373** [Tongjilibo/bert4torch#127]
。

**Comment by Tongjilibo** [comment]
你是说直接加载量化之后的权重文件吗？比如[THUDM/chatglm-6b-int4](https://huggingface.co/THUDM/chatglm-6b-int4)这种吗？

**Comment by Tongjilibo** [comment]
已经添加，欢迎试用~

**Comment by a2012456373** [comment]
我使用llama，然后使用你的量化方法，然后保存量化后的模型，然后没法加载。这种可以搞吗？glm6b那个模型是 可以这样弄得
model = LlamaForCausalLM.from_pretrained(ckpt,device_map='auto')
model = model.quantize(8)
import os
directory = "123"
os.makedirs(directory, exist_ok=True)
# 保存tokenizer和model的配置文件和权重
#with tp.save_tensor_parallel(model):
tokenizer.save_pretrained(directory)
model.config.save_pretrained(directory)
model.save_pretrained(directory)
#################################
model = LlamaForCausalLM.from_pretrained(ckpt,device_map='auto')

Some weights of the model checkpoint at ./123 were not used when initializing LlamaForCausalLM: ['model.layers.38.self_attn.k_proj.weight_scale', 'model.layers.34.self_attn.k_proj.weight_scale', 'model.layers.32.self_attn.o_proj.weight_scale', 'model.layers.30.self_attn.v_proj.weight_scale', 'model.layers.12.self_attn.q_proj.weight_scale',..............

**Comment by Tongjilibo** [comment]
可以是可以的，但是这个其实和bert4torch没啥关系？我看你的代码，感觉是你想把chatglm6b那套量化方法移植到llama来，用hf的加载方式是吗？

**Comment by a2012456373** [comment]
（老哥回的好快啊，赞美）是的，在尝试把glm的量化移植到llama，我自己先试试。

**Comment by Tongjilibo** [comment]
嗯嗯，那你先试试看，这个issue我先close了哈~
