### ISSUE TITLE
bert+crf  做ner任务的基础案例 出现loss 陡增情况

### ISSUE THREAD

**Issue by zbbwss** [Tongjilibo/bert4torch#13]
![image](https://user-images.githubusercontent.com/42829645/179023257-b3563c29-569c-42ae-848d-b1f1fea1d5b6.png)

**Comment by zbbwss** [comment]
代码 使用的是  task_sequence_labeling_ner_crf.py

**Comment by Tongjilibo** [comment]
> 数据集用的你 代码里面的数据china-people-daily-ner-corpus.tar.gz

方便贴你下你用的bert4torch的版本，是pip的还是用的git最新的？

**Comment by Tongjilibo** [comment]
> 数据集用的你 代码里面的数据china-people-daily-ner-corpus.tar.gz

方便贴你下你用的bert4torch的版本，是pip的还是用的git最新的？如果用的是旧版本可以用git最新的代码试一下，我这边也验证下看看

**Comment by zbbwss** [comment]
git clone https://github.com/Tongjilibo/bert4torch   使用是这个

**Comment by Tongjilibo** [comment]
> git clone https://github.com/Tongjilibo/bert4torch 使用这种方式直接得到包，然后版本 0.1.7
我这测试下来的确存在这个bug，我先换了个CRF，目前测下来应该是可以的，你可以用最新的git代码测试一下看看
![image](https://user-images.githubusercontent.com/33407736/179342330-fc230b28-bcc2-4ed5-9fc8-0e46e5d2c055.png)
