### ISSUE TITLE
Sohu_2022_ABSA   sequence_padding的疑惑

### ISSUE THREAD

**Issue by huaweiboy** [Tongjilibo/bert4torch#130]
![image](https://github.com/Tongjilibo/bert4torch/assets/5070286/edcc2019-48b2-4e71-b845-643875738c2b)
hugging face这边的pad_id是5，但是代码里collate_fn是用0填充的，是不是有点问题？
![image](https://github.com/Tongjilibo/bert4torch/assets/5070286/322e0a9e-78fb-4078-8c77-dc158dfd2d15)

**Comment by Tongjilibo** [comment]
您好，您说的是对的，我这边已经修改了，之前在[xlnet分类](https://github.com/Tongjilibo/bert4torch/blob/master/examples/sentence_classfication/task_sentiment_classification_xlnet.py)中有设置，这边忘记了没有修改掉，您可以再看下
