### ISSUE TITLE
RDropLoss函数实现 bug

### ISSUE THREAD

**Issue by ZayIsAllYouNeed** [Tongjilibo/bert4torch#138]
bert4torch/losses.py 里的 RDropLoss 实现，第 186 行
loss_sup = self.loss_sup(y_pred1, y_true) 应该改为：
loss_sup = (self.loss_sup(y_pred1, y_true) + self.loss_sup(y_pred2, y_true))  /  2

**Comment by Tongjilibo** [comment]
好的，已经修改
