### ISSUE TITLE
print_trainable_parameters 函数缺失

### ISSUE THREAD

**Issue by ZayIsAllYouNeed** [Tongjilibo/bert4torch#139]
在bert4torch/models.py有
from bert4torch.snippets import print_trainable_parameters，
但是在 bert4torch.snippets 没有 print_trainable_parameters 这个函数的定义

**Comment by ZayIsAllYouNeed** [comment]
另外的其他函数，比如 DottableDict、colorful 都没有找到诶

**Comment by ZayIsAllYouNeed** [comment]
> 

你好，我确实是git过来的，但是没找到这些函数，您可以看下当前版本仓库的bert4torch.snippets是否有print_trainable_parameters函数

**Comment by ZayIsAllYouNeed** [comment]
> 

你好，我确实是git过来的，但是没找到这些函数，您可以看下当前版本仓库的bert4torch.snippets是否有print_trainable_parameters函数

**Comment by Tongjilibo** [comment]
还需要git版的torch4keras

**Comment by ZayIsAllYouNeed** [comment]
嗯嗯，我之前没更新torch4keras，现在更新完后跑通了。谢谢～
