### ISSUE TITLE
在CMeIE1.0数据集上使用TPLinker实现信息抽取任务，precision很高，recall极低

### ISSUE THREAD

**Issue by JasonHI7** [Tongjilibo/bert4torch#142]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: CentOS7
- 你使用的**Python**版本: python3.7
- 你使用的**Pytorch**版本: 1.12.1
- 你使用的**bert4torch**版本: 0.2.8
- 你加载的**预训练模型**:Bert-base-Chinese

### 核心代码
```python
# 仅修改加载数据集部分代码（spo['object']['@value']）
class MyDataset(ListDataset):
    @staticmethod
    def load_data(filename):
        """加载数据
        单条格式：{'text': text, 'spo_list': [(s, p, o)]}
        """
        D = []
        with open(filename, encoding='utf-8') as f:
            for l in f:
                l = json.loads(l)
                D.append({'text': l['text'],
                          'spo_list': [(spo['subject'], spo['predicate'], spo['object']['@value']) for spo in l['spo_list']]})
        return D
```

### 输出信息
```shell
valid/f1-score=0.00038	valid/precision=1.00000	valid/recall=0.00019
```

### 自我尝试
并未改动其他任何源代码，训练轮数和学习率对于最终结果也无影响

**Comment by Tongjilibo** [comment]
我之前用百度数据集测试，效果一般而且收敛较慢，所以没有进一步的测试了，建议你先换个别的方法跑着，我有时间用你这个数据集看下

**Comment by JasonHI7** [comment]
> 我之前用百度数据集测试，效果一般而且收敛较慢，所以没有进一步的测试了，建议你先换个别的方法跑着，我有时间用你这个数据集看下

是数据集里有漏标导致的，感谢

**Comment by Tongjilibo** [comment]
> > 我之前用百度数据集测试，效果一般而且收敛较慢，所以没有进一步的测试了，建议你先换个别的方法跑着，我有时间用你这个数据集看下
> 
> 是数据集里有漏标导致的，感谢

你是说是数据集的问题是吗？模型实现没问题是吧？

**Comment by JasonHI7** [comment]
> > > 我之前用百度数据集测试，效果一般而且收敛较慢，所以没有进一步的测试了，建议你先换个别的方法跑着，我有时间用你这个数据集看下
> > 
> > 
> > 是数据集里有漏标导致的，感谢
> 
> 你是说是数据集的问题是吗？模型实现没问题是吧？

是的
