### ISSUE TITLE
询问一个bert4torch和bert4keras的差异

### ISSUE THREAD

**Issue by pql123** [Tongjilibo/bert4torch#145]
我在使用bert4keras加载 bert-base-chinese，做分类任务时，会查出显存，但是使用bert4torch就可以正常训练，是torch显存优化的比tensorflow好？还是bert4torch会冻结某些参数嘛？我的显卡是1660 6g显存。

### 基本信息
- 你使用的**操作系统**:  windows
- 你使用的**Python**版本: 3.8
- 你使用的**Pytorch**版本:   1.9.1+cu111
- 你使用的**bert4torch**版本:  0.2.7.post2 
- 你加载的**预训练模型**: bert-base-chinese

**Comment by Tongjilibo** [comment]
bert4torch不会冻结参数，至于你说的显存问题，基于以上我目前也判别不出来
