### ISSUE TITLE
basic_masked_language_model.py

### ISSUE THREAD

**Issue by chongzicbo** [Tongjilibo/bert4torch#15]
这个example中
输入：[CLS]科学[MASK][MASK]是第一生产力[SEP]
预测出来的结果是，，两个逗号,而不是技术
使用的模型是hugging face 模型库中的bert-base-chinese。
模型加载过程中出现大量警告：
![image](https://user-images.githubusercontent.com/22750382/183279067-c84bad9e-4958-4eec-9581-3b49a65b7d69.png)
请问只是啥问题？

**Comment by Tongjilibo** [comment]
警告是因为没有成功加载预训练参数，因为你用的bert-base-chinese的权重的key和本框架没有完全对齐，导致Laynorm层的权重和偏置未成功加载，可以使用[转化脚本](https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/convert_bert-base-chinese.py)修改一下，本项目使用到的[部分数据集下载链接](https://github.com/Tongjilibo/bert4torch/blob/master/examples/README.md)，[直接加载的checkpoint清单](https://github.com/Tongjilibo/bert4torch)

之前issue中有提及：#2
