### ISSUE TITLE
显示每个epoch的已用时间和预估剩余时间

### ISSUE THREAD

**Issue by zhouyiyuan-mt** [Tongjilibo/bert4torch#152]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Pytorch**版本: 
- 你使用的**bert4torch**版本: 
- 你加载的**预训练模型**:

目前进度条只会显示预估剩余时间，但是不会显示已用时间。有时候想预估一下跑一个epoch的时间，但是又不想真的跑完，这个功能就很有用，可以参考yolo的进度条设计：

=============================================
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        0/2      35.1G     0.1095      2.964      1.084        717        640:   1%|          | 13/2465 [00:20<1:12:20,  1.77s/it]

这样跑几个step就能预估跑一个epoch大概需要的时间00:20+1:12:20 = 1:12:40。

**Comment by Tongjilibo** [comment]
从几点来回答您的问题
1. 默认的进度条是ETA，显示的是预计剩余的时间，其实刚刚开始跑几个step就可以测算出来epoch的时间的，我感觉对结果影响不大
2. 如果是已经跑了一段时间，其实每个epoch开始的时候，会打印起始时间，也可以自己测算
3. 可以通过`model.complie(progbar_config={'bar': 'tqdm'})`，可以调用tqdm进度条，可以直接实现您说的功能

当然我也会看下后续实现您说的功能，以上回答供参考

**Comment by Tongjilibo** [comment]
我这边这torch4keras中，调整了一下逻辑，在下个版本中会默认增加已经消耗的时间，形式如下：
```
2023-09-28 00:49:37 - Epoch: 1/5
 1379/20000 [=>............................] - ETA: 0:05<1:19 - loss: 0.5137 - acc: 0.8450
```

**Comment by zhouyiyuan-mt** [comment]
非常感谢！
