### ISSUE TITLE
chinese-xlnet-mid载入

### ISSUE THREAD

**Issue by chosenone75** [Tongjilibo/bert4torch#153]
请教一下大佬，chinese-xlnet-mid的config需要额外配置吗，直接载入会报如下错误
TypeError: __init__() missing 5 required positional arguments: 'hidden_size', 'num_hidden_layers', 'num_attention_heads', 'intermediate_size', and 'hidden_act'

**Comment by Lxhnnn** [comment]
请问怎么解决的呢
