### ISSUE TITLE
XLnet分类报错

### ISSUE THREAD

**Issue by Lxhnnn** [Tongjilibo/bert4torch#154]
TypeError: __init__() missing 6 required positional arguments: 'vocab_size', 'hidden_size', 'num_hidden_layers', 'num_attention_heads
', 'intermediate_size', and 'hidden_act'

**Comment by Tongjilibo** [comment]
> TypeError: __init__() missing 6 required positional arguments: 'vocab_size', 'hidden_size', 'num_hidden_layers', 'num_attention_heads
> ', 'intermediate_size', and 'hidden_act'
> 
> 

需要配置config文件的，我提供了一个convert脚本可以参考

**Comment by Lxhnnn** [comment]
该脚本文件在哪呢

**Comment by Tongjilibo** [comment]
> 该脚本文件在哪呢

有个convert文件夹下，你用xlnet就用convert_xlnet的就可以

**Comment by Lxhnnn** [comment]
好的，感谢！
