### ISSUE TITLE
simbert微调问题

### ISSUE THREAD

**Issue by Lxhnnn** [Tongjilibo/bert4torch#155]
seq2seq下的task_seq2seq_simbert.py
报错代码行：loss = F.cross_entropy(similarities, y_true)

原因：similarities和y_true维度一致，报错：
报错结果：RuntimeError: multi-target not supported at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:15

**Comment by Tongjilibo** [comment]
你好，这边我跑了下没这个问题

**Comment by Lxhnnn** [comment]
好的，谢谢
