### ISSUE TITLE
运行t5-pegasus报错

### ISSUE THREAD

**Issue by Pzeyang** [Tongjilibo/bert4torch#16]
![image](https://user-images.githubusercontent.com/42735831/183295825-d4dcdc39-a14e-4c43-a428-9d96ca8f77ef.png)
您好，通过您给定convert_t5_pegasus转化成立pytorch_model.bin，此处config.json我沿用了base版本的config.json，这个错把
"hidden_act": ["gelu", "linear"]改成"hidden_act": "gelu"后出这个错
![image](https://user-images.githubusercontent.com/42735831/183296021-a2fd5313-80ba-4efa-b0ea-d106170ddf06.png)
望解答，谢谢!

**Comment by Tongjilibo** [comment]
你使用这个config文件试一下，我这边测试是可以使用，后续我把使用的config整理下，都发出来
```json
{
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 2048,
  "num_attention_heads": 12,
  "attention_head_size": 64,
  "num_hidden_layers": 12,
  "vocab_size": 50000,
  "hidden_act": "gelu",
  "relative_attention_num_buckets": 32
}
```

**Comment by Pzeyang** [comment]
可以了，谢谢
