### ISSUE TITLE
bert4torch/examples/llm /task_chatglm2_lora.py中的config_path = dir_path + 'bert4torch_config.json' 在哪里？

### ISSUE THREAD

**Issue by zysNLP** [Tongjilibo/bert4torch#163]
如题，谢谢！

**Comment by Tongjilibo** [comment]
需要自定义`config`的，均在`basic`下，你需要的[文件路径](https://github.com/Tongjilibo/bert4torch/tree/master/examples/basic/glm/chatglm2-6B)

**Comment by zhadandeiren** [comment]
同问，上面的路径没有了，请问在哪里可以查看，谢谢！

**Comment by zysNLP** [comment]
@zhadandeiren https://huggingface.co/Tongjilibo/bert4torch_config/tree/main/chatglm2-6b，跑到这里去了，看readme的那张表
