### ISSUE TITLE
请求大佬写个NER指针网络的预测代码

### ISSUE THREAD

**Issue by Echo-she** [Tongjilibo/bert4torch#167]

**Comment by Tongjilibo** [comment]
可以直接参考evaluate的内容的，可以解析得到start, end，和实体类别，这样你直接把这段tokens decode一下就能拿到对应的实体内容了

**Comment by Echo-she** [comment]
是类似下面代码这样子的吗：model.eval()
with torch.no_grad():
    pp = model(text_tokenizer['input_ids'].to(device))[0].cpu()

scores = pp
threshold = 0.5
mapping = offset_mapping

for i, score in enumerate(scores):
    R = set()
    for start, end in zip(*np.where(score.cpu() > threshold)):
        R.add((start, end, categories_id2label[i]))  
    print(R)

**Comment by Tongjilibo** [comment]
和你写的差不多，我这里增加了一个inference的函数，供参考

**Comment by Echo-she** [comment]
好的，感谢大佬
