### ISSUE TITLE
苏神的多任务预训练有计划实现吗？谢谢。

### ISSUE THREAD

**Issue by alei76** [Tongjilibo/bert4torch#19]
多任务预训练  https://github.com/ZhuiyiTechnology/roformer-v2/tree/main/multi-task

**Comment by Tongjilibo** [comment]
> 多任务预训练 https://github.com/ZhuiyiTechnology/roformer-v2/tree/main/multi-task

我初步看了下，感觉用到的场景不会太多，有时间的话我实现下，不过基于bert4torch改写感觉不复杂，也可以自行实现啊

**Comment by alei76** [comment]
好的，垂直领域单模型多任务用到的场景挺多的，多谢呀！
