### ISSUE TITLE
如果是自定义的acc,loss怎么用

### ISSUE THREAD

**Issue by reporter-law** [Tongjilibo/bert4torch#21]
例如：
想象keras一样直接将自定义函数作为模型的评估函数该怎么做？

该如何修改
def accuracy(y_pred, y_true):
    y_pred = torch.where(y_pred>0.5,torch.ones_like(y_pred,dtype = torch.float32),
                      torch.zeros_like(y_pred,dtype = torch.float32))
    acc = torch.mean(1-torch.abs(y_true-y_pred))
    return acc

model.compile(
    loss=nn.CrossEntropyLoss(),
    optimizer=optim.Adam(model.parameters(), lr=2e-5),
    metrics={LogLoss}
)
![image](https://user-images.githubusercontent.com/61373015/187597726-e2be2802-cb40-46ba-9544-24380aa7203b.png)

**Comment by Tongjilibo** [comment]
- 刚刚支持到，你可以用最新的git代码测试下看看，调用方式如下
- 原来metrics是LIST[STR]输入，现在支持LIST[STR]、DICT、LIST[STR, DICT]的混合输入，元素为STR类型的目前是只支持accuracy，注意自定义metrics函数的返回值需要是数值型`int/float`
```python
def acc(preds, labels):
    return random.random()

def f1(preds, labels):
    return random.random()

model.compile(loss=Loss(), optimizer=optim.Adam(model.parameters(), lr=2e-5), metrics={'acc': acc, 'f1': f1})
```

**Comment by reporter-law** [comment]
# 这又有一个新的问题：就是该如何支持GPU上运行自定义的metrics函数

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by Tongjilibo** [comment]
> # 这又有一个新的问题：就是该如何支持GPU上运行自定义的metrics函数
> TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

metrics是可以用gpu来跑的啊，我看错误代码是说你把tensor转numpy时候需要先放到cpu上，你可以用gpu算出来一个标量的Tensor直接.item()就可以了吧

**Comment by reporter-law** [comment]
感谢Tongjilibo 大佬，还要加强torch的学习
