### ISSUE TITLE
使用task_sequence_labeling_ner_global_pointer.py训练结果为0

### ISSUE THREAD

**Issue by hurun** [Tongjilibo/bert4torch#22]
使用task_sequence_labeling_ner_global_pointer.py脚本做尝试
修改位置及代码如下
1、加载bert模型为huggingface上面的模型权重
        self.bert_dir = "/home/BERT/bert_torch/bert-base-chinese/"
        self.config_path = self.bert_dir + 'config.json'
        self.checkpoint_path = self.bert_dir + 'pytorch_model.bin'
        self.dict_path = self.bert_dir + 'vocab.txt'
2、修改model.fit参数
     model.fit(train_dataloader, epochs=20, steps_per_epoch=5, callbacks=[evaluator])
3、完全运行结果，部分截图如下
      1/5 [=====>........................] - ETA: 0s - loss: 2.5862
      2/5 [===========>..................] - ETA: 0s - loss: 2.5127
      3/5 [=================>............] - ETA: 0s - loss: 2.7961
      4/5 [=======================>......] - ETA: 0s - loss: 2.8367
      5/5 [==============================] - 1s 125ms/step - loss: 2.4887
      [val] f1: 0.00000, p: 0.00000 r: 0.00000 best_f1: 0.00000
      ============Finish Training=============
      Process finished with exit code 0
系统：ubuntu 20.0.4
pytorch版本：1.11.0+cu113
python: 3.7

想请教下是哪里的问题，导致f1结果一直为0

**Comment by Tongjilibo** [comment]
bert-base-chinese你有用转换脚本转下权重吗？https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/convert_bert-base-chinese.py

**Comment by Tongjilibo** [comment]
还有就是steps_per_epoch表示每个epoch跑的step数量，你设置为5太小了，可以不设置(默认为None)表示把dataloader消费一遍作为一个epoch

**Comment by Tongjilibo** [comment]
我这边跑了下是没问题的，还有就是steps_per_epoch表示每个epoch跑的step数量，你设置为5太小了，可以不设置(默认为None)表示把dataloader消费一遍作为一个epoch

**Comment by hurun** [comment]
设置为None会出现断言提示，后面程序停止运行

**Comment by Tongjilibo** [comment]
> 设置为None会出现断言提示，后面程序停止运行 Traceback (most recent call last): File "/data/Projects/bert4torch-master/examples/sequence_labeling/task_sequence_labeling_ner_global_pointer.py", line 153, in model.fit(train_dataloader, epochs=20, steps_per_epoch=None, callbacks=[evaluator]) File "/data/Projects/bert4torch-master/bert4torch/models.py", line 213, in fit assert steps_per_epoch is not None, 'Either train_dataloader.dataset has attr "**len**" or steps_per_epoch is not None' AssertionError: Either train_dataloader.dataset has attr "**len**" or steps_per_epoch is not None

git clone下最新的代码，这个问题是昨天由此改动导致的，用最新的试下看看

**Comment by hurun** [comment]
更新代码后，解决了提问的问题，但第一轮训练的f1值为0，看起来有点奇怪
1304/1304 [==============================] - 163s 125ms/step - loss: 2.8868
[val] f1: 0.00000, p: 0.00000 r: 0.00000 best_f1: 0.00000
2022-09-02 14:14:52 - Epoch: 2/20

**Comment by Tongjilibo** [comment]
你权重也按照上面说的转换过了是吗？或者你换个哈工大的bert试下，再有问题可以知乎上私我

**Comment by hurun** [comment]
感谢解答，在其他电脑运行正常
