### ISSUE TITLE
运行W2NER示例是报错ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by FalAnge1217** [Tongjilibo/bert4torch#23]
如题
![image](https://user-images.githubusercontent.com/82627285/188100092-aaaf099d-50d9-4652-aeee-81789c8b10fb.png)

**Comment by Tongjilibo** [comment]
我给的示例数据集是[人民日报数据集](http://s3.bmio.net/kashgari/china-people-daily-ner-corpus.tar.gz)，你换成别的数据集，数据格式不一样就需要自己修改读数据的代码

**Comment by FalAnge1217** [comment]
大佬，之前搁置了，今天来跑，用的你给的数据，有个错误没解决
`TypeError: compile() got an unexpected keyword argument 'clip_grad_norm'`
![图片](https://user-images.githubusercontent.com/82627285/194748595-bbf4ff3c-ed80-4975-ac4c-0186b2f58308.png)

**Comment by Tongjilibo** [comment]
你使用的bert4torch版本是什么？

**Comment by Tongjilibo** [comment]
如果不是最新版本，使用最新版试一下

**Comment by FalAnge1217** [comment]
```
bert4torch   0.2.2
torch    1.11.0+cu113
```
换了最新版本还是一样的错，难道是我torch版本太高了？我试试torch1.10.1

**Comment by FalAnge1217** [comment]
换了torch1.10.1 还是一样的问题

**Comment by Tongjilibo** [comment]
不是torch版本的问题，我的代码里面是有这个参数的，刚跑了下我这是没有问题的，你可以断点调试下看看，看看这个complie是调用的哪里的
