### ISSUE TITLE
使用task_seq2seq_autotitle_csl_uer_t5.py代码，加载uer/t5-small-chinese-cluecorpussmall中的config.json报错

### ISSUE THREAD

**Issue by semon2019** [Tongjilibo/bert4torch#25]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/46260207/189554765-2e4534b8-7fbb-4016-9410-2cc54c307415.png">

好像该json文件中确实没有 'hidden_size', 'num_hidden_layers', 'num_attention_heads', 'intrmediate_size', and 'hidden_act'这样几个参数

**Comment by Tongjilibo** [comment]
https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/PLM_config.md，readme里面应该标记base版本的

**Comment by semon2019** [comment]
![image](https://user-images.githubusercontent.com/46260207/189809233-bbf6ffc8-87c6-40da-8147-255300d8e050.png)
将config改为如上所示，然后t5用的是uer/t5-base-chinese-cluecorpussmall，但是还会报如下错误：
![image](https://user-images.githubusercontent.com/46260207/189809358-efc5af04-ee55-4c01-8f96-7392cf7988bb.png)

**Comment by Tongjilibo** [comment]
看错误是下标越界，猜测你看下vocab.txt最后是不是有两个换行，如果是你保留一个换行就可以了

**Comment by semon2019** [comment]
> Owner
多谢，解决了！！

**Comment by XuJianzhi** [comment]
> 看错误是下标越界，猜测你看下vocab.txt最后是不是有两个换行，如果是你保留一个换行就可以了

这咋看出的？太神了吧

**Comment by Tongjilibo** [comment]
以前也遇到过

**Comment by Tongjilibo** [comment]
> > 看错误是下标越界，猜测你看下vocab.txt最后是不是有两个换行，如果是你保留一个换行就可以了
> 
> 这咋看出的？太神了吧

以前也遇到过
