### ISSUE TITLE
原始数据

### ISSUE THREAD

**Issue by Rockiie** [Tongjilibo/bert4torch#26]
您好，请问能否发一下您用于训练和测试的原始数据集呢？主要是想了解一下您是如何跑出如此高的准确率的，谢谢！

**Comment by Tongjilibo** [comment]
https://github.com/Tongjilibo/bert4torch/blob/master/examples/README.md

**Comment by Rockiie** [comment]
了解了，谢谢！

**Comment by Rockiie** [comment]
> https://github.com/Tongjilibo/bert4torch/blob/master/examples/README.md
您好，我想问一下，FinanceFAQ里的q_std和q_sim是如何从原始数据里得到的呢？谢谢！

**Comment by Tongjilibo** [comment]
> https://github.com/Tongjilibo/bert4torch/blob/master/examples/README.md
> 您好，我想问一下，FinanceFAQ里的q_std和q_sim是如何从原始数据里得到的呢？谢谢！

不好意思，这个数据不开源，我回头放几条数据行示例一下

**Comment by Rockiie** [comment]
> > https://github.com/Tongjilibo/bert4torch/blob/master/examples/README.md
> > 您好，我想问一下，FinanceFAQ里的q_std和q_sim是如何从原始数据里得到的呢？谢谢！
> 
> 不好意思，这个数据不开源，我回头放几条数据行示例一下

好的好的，明白了，谢谢
