### ISSUE TITLE
这个地方没有将随机种子赋值给seed

### ISSUE THREAD

**Issue by iamqiz** [Tongjilibo/bert4torch#27]
这个地方没有将随机种子赋值给seed
https://github.com/Tongjilibo/bert4torch/blob/ab4f74b7d23c2b9705305c37a2d132dd0c6be874/bert4torch/snippets.py#L1275

**Comment by Tongjilibo** [comment]
> 这个地方没有将随机种子赋值给seed
> 
> https://github.com/Tongjilibo/bert4torch/blob/ab4f74b7d23c2b9705305c37a2d132dd0c6be874/bert4torch/snippets.py#L1275

已修复~
