### ISSUE TITLE
疑似错误

### ISSUE THREAD

**Issue by iamqiz** [Tongjilibo/bert4torch#29]
112行
https://github.com/Tongjilibo/bert4torch/blob/a1d66a761a77f0571ef9dc9b431089e23fd6efcb/examples/tutorials/tutorials_small_tips.py#L111-L112

**Comment by Tongjilibo** [comment]
> 112行
> 
> https://github.com/Tongjilibo/bert4torch/blob/a1d66a761a77f0571ef9dc9b431089e23fd6efcb/examples/tutorials/tutorials_small_tips.py#L111-L112

已修复，细心，谢谢~
