### ISSUE TITLE
用到的数据集能下载吗

### ISSUE THREAD

**Issue by macheng6** [Tongjilibo/bert4torch#3]

**Comment by Tongjilibo** [comment]
我都是用的公开数据集，网上也能找到的，部分数据我是提供了链接，或者访问bert4keras项目查一下；后续我整理好了会放在readme里面的

**Comment by macheng6** [comment]
> 我都是用的公开数据集，网上也能找到的，部分数据我是提供了链接，或者访问bert4keras项目查一下；后续我整理好了会放在readme里面的

支持使用transformers上的checkpoint来初始化模型吗？

**Comment by Tongjilibo** [comment]
> > 我都是用的公开数据集，网上也能找到的，部分数据我是提供了链接，或者访问bert4keras项目查一下；后续我整理好了会放在readme里面的
> 
> 支持使用transformers上的checkpoint来初始化模型吗？

可以的，常见的bert和roberta模型这些都是可以的，其实主要是state_dict()中key的名称是否一致，如果你用了不支持，欢迎反馈哈

**Comment by Tongjilibo** [comment]
> > > 我都是用的公开数据集，网上也能找到的，部分数据我是提供了链接，或者访问bert4keras项目查一下；后续我整理好了会放在readme里面的
> > 
> > 
> > 支持使用transformers上的checkpoint来初始化模型吗？
> 
> 可以的，常见的bert和roberta模型这些都是可以的，其实主要是state_dict()中key的名称是否一致，如果你用了不支持，欢迎反馈哈

您好，再次反馈一下，由于不同渠道保存权重的key值有可能存在不同，所以transformers中有的模型不能直接加载，解决方案一个是部分权重我在example/conver目录下提供了转换脚本，目前我开发使用的模型bert是google原版权重chinese_L-12_H-768_A-12的pytorch版本，一个是哈工大的chinese-roberta-wwm-ext-base， robert是哈工大的chinese-roberta-wwm-ext，后续我尽快整理出我用的权重

还有一种折衷方式，就是直接调用transformers库中模型，不过这样有点失去了使用bert4torch框架的乐趣，如下所示
- [加载transformers模型进行训练](https://github.com/Tongjilibo/bert4torch/blob/master/examples/others/task_load_transformers_model.py)
```python
from transformers import AutoModelForSequenceClassification
class Model(BaseModel):
    def __init__(self):
        super().__init__()
        self.bert = AutoModelForSequenceClassification.from_pretrained("file_path", num_labels=2)
    
    def forward(self, token_ids, attention_mask, segment_ids):
        output = self.bert(input_ids=token_ids, attention_mask=attention_mask, token_type_ids=segment_ids)
        return output.logits
```

**Comment by Tongjilibo** [comment]
> 我都是用的公开数据集，网上也能找到的，部分数据我是提供了链接，或者访问bert4keras项目查一下；后续我整理好了会放在readme里面的

部分数据集[下载链接](https://github.com/Tongjilibo/bert4torch/blob/master/examples/README.md)
