### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by iamqiz** [Tongjilibo/bert4torch#30]
115 行被注释掉了, 后面inference要用到这个文件
https://github.com/Tongjilibo/bert4torch/blob/5953abe14ca72f727604dd7c65604c46824832f5/examples/tutorials/tutorials_small_tips.py#L108-L116

**Comment by Tongjilibo** [comment]
好的，不过一般是我不想本地跑代码时候保存太多ckpt所以注释掉的（其他脚本我也注释掉了），真正使用的时候可以自行解开注释

**Comment by iamqiz** [comment]
> inference

有道理😉
