### ISSUE TITLE
t5_pegasus_small 支持问题

### ISSUE THREAD

**Issue by fuhaito7** [Tongjilibo/bert4torch#32]
你好，我想用t5_pegasus_small做一个seq2seq任务，config.json文件如下：
{
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 512,
  "initializer_range": 0.02,
  "intermediate_size": 1024,
  "num_attention_heads": 6,
  "attention_head_size": 64,
  "num_hidden_layers": 8,
  "vocab_size": 50000,
  "hidden_act": "gelu",
  "relative_attention_num_buckets": 32
}
，但是运行时在layer层会抛assert hidden_size % num_attention_heads == 0  错误，请问是配置文件哪里不对吗

**Comment by fuhaito7** [comment]
权重文件我也是通过convert里面的脚本转换的

**Comment by Tongjilibo** [comment]
之前的框架是不支持的(hidden_size必须是注意力头的整数倍)，目前已经更新了，你可以重新git clone试一下，对应的config如下：
```json
{
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 512,
  "initializer_range": 0.02,
  "intermediate_size": 1024,
  "num_attention_heads": 6,
  "attention_head_size": 64,
  "num_hidden_layers": 8,
  "vocab_size": 50000,
  "relative_attention_num_buckets": 32,
  "attention_scale":  false,
  "is_dropout": true
}
```
此外还提供了预训练模型测试文件https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_t5_pegasus.py

**Comment by fuhaito7** [comment]
谢谢大佬，解决了。
