### ISSUE TITLE
怎么加载hugface的Bert模型啊？波哥帮帮我

### ISSUE THREAD

**Issue by 0614lsn** [Tongjilibo/bert4torch#33]
我跑的是task_sequence_labeling_ner_global_pointer.py 
我的代码里就改了我下载的bert的路径（我用的是绝对路径）和在定义bert这一行(加了个model="bert")
```python
config_path = '/mnt/hdd0/lsn/bert/bert-base-uncased/config.json'
checkpoint_path = '/mnt/hdd0/lsn/bert/bert-base-uncased/pytorch_model.bin'
dict_path = '/mnt/hdd0/lsn/bert/bert-base-uncased/vocab.txt'

self.bert = build_transformer_model(config_path=config_path, checkpoint_path=checkpoint_path, model='bert', segment_vocab_size=0)
```

然后运行后报一堆[warning]，类似下面这样的
[WARNIMG] bert.embeddings.LayerNorm.weight not found in pretrain models
[WARNIMG] bert.embeddings.LayerNorm.bias not found in pretrain models
[WARNIMG] bert.encoder.layer.0.attention.output.LayerNorm.weight not found in pretrain models
[WARNIMG] bert.encoder.layer.0.attention.output.LayerNorm.bias not found in pretrain models
[WARNIMG] bert.encoder.layer.0.output.LayerNorm.weight not found in pretrain models
[WARNIMG] bert.encoder.layer.0.output.LayerNorm.bias not found in pretrain models

**Comment by 0614lsn** [comment]
跑了2，3个epoch结果p，r，f1都是0

**Comment by Tongjilibo** [comment]
#15 参考这个转换下、不过你这个模型是个英文的，我没有太测试Tokenizer的结果

**Comment by 0614lsn** [comment]
好的 我试试

**Comment by 0614lsn** [comment]
谢谢波哥  我大概知道问题了 一是我用的英文的bert权重 二是LN的weight和bias的转化问题 我改正一下 明天再试试结果

**Comment by 0614lsn** [comment]
波哥 我还有一个问题 google原版的tf版的bert转为torch版后 和hugface直接下载的torch版bert有区别吗？

**Comment by Tongjilibo** [comment]
> 波哥 我还有一个问题 google原版的tf版的bert转为torch版后 和hugface直接下载的torch版bert有区别吗？

本地比对了下是一样的，更新了下Readme
