### ISSUE TITLE
验证evaluate推理速度第一次快，其他时候非常慢的问题

### ISSUE THREAD

**Issue by fuhaito7** [Tongjilibo/bert4torch#34]
你好，波哥，请问为啥self.evaluate(valid_dataset.data[:valid_len])，第一次推理验证集时速度快，第二次推理同样的验证集时速度只有前一次的二十分之一左右，evaluate代码如下
    def evaluate(self, data):
        total = 0
        rouge_1, rouge_2, rouge_l, bleu = 0, 0, 0, 0
        for title, content in tqdm(data):
            total += 1
            title = ' '.join(title).lower()
            # with torch.no_grad():
            pred_title = ' '.join(autosumm.generate(content)).lower()
            if pred_title.strip():
                scores = self.rouge.get_scores(hyps=pred_title, refs=title)
                rouge_1 += scores[0]['rouge-1']['f']
                rouge_2 += scores[0]['rouge-2']['f']
                rouge_l += scores[0]['rouge-l']['f']
                bleu += sentence_bleu(references=[title.split(' ')], hypothesis=pred_title.split(' '),
                                      smoothing_function=self.smooth)
        rouge_1, rouge_2, rouge_l, bleu = rouge_1 / total, rouge_2 / total, rouge_l / total, bleu / total
        return {'rouge-1': rouge_1, 'rouge-2': rouge_2, 'rouge-l': rouge_l, 'bleu': bleu}
![微信截图_20220919220951](https://user-images.githubusercontent.com/91183532/191039588-606ed9c2-59b9-46b0-8e62-8fa5f9203df9.png)

**Comment by Tongjilibo** [comment]
提供的信息下不了结论，我这边还没能复现你的问题，可以提供完整代码吗

**Comment by fuhaito7** [comment]
我刚才多跑了一些step，发现除了第二次慢之外，后面就恢复正常了，麻烦大佬了.
