### ISSUE TITLE
加入词性信息

### ISSUE THREAD

**Issue by lili-li-cpu** [Tongjilibo/bert4torch#38]
提问时请尽可能提供如下信息：

![} Z1@4JR)%$K4X1A@8(_68A](https://user-images.githubusercontent.com/66951248/191744285-409af3ec-7b25-4b8a-9b2f-2b686bb0db67.png)

**Comment by lili-li-cpu** [comment]
我将batch设为12时，得到的batch_token_ids,batch_segment_ids维度中的batch都是11
![Uploading image.png…]()

**Comment by Tongjilibo** [comment]
这个batchsize的问题debug看下啊？感觉应该是数据处理上的问题，你断点调试下看看，我刚刚重新跑了下我的词性信息的example可以正常执行的

**Comment by lili-li-cpu** [comment]
![DJTY@YNATZA1UABOWIPVTKT](https://user-images.githubusercontent.com/66951248/191764555-aa85a2af-1cf7-441f-993b-c35da5b5b87b.png)

**Comment by lili-li-cpu** [comment]
这个

**Comment by lili-li-cpu** [comment]
关系抽取模型casrel里面的

**Comment by lili-li-cpu** [comment]
谢谢，我明天尝试一下

**Comment by lili-li-cpu** [comment]
我把加到if spoes下面确实可以，谢谢

**Comment by Tongjilibo** [comment]
好的
