### ISSUE TITLE
请问class CRF(nn.Module):是从哪里移植过来的？

### ISSUE THREAD

**Issue by kangyishuai** [Tongjilibo/bert4torch#4]
麻烦您给个链接，我想看看移植过来之前的源码。
主要是想知道转移矩阵这里为什么要+2：
init_transitions = torch.zeros(self.num_labels + 2, self.num_labels + 2)
因为看过其他实现，头一次看到+2的情况，您在代码中也注释了是要加首尾，但我不知道加首尾是要解决什么问题。

**Comment by chironma** [comment]
我用这里的提供的crf，loss不收敛；但是用 [BERT_NER_Pytorch](https://github.com/lonePatient/BERT-NER-Pytorch/blob/master/models/layers/crf.py) 提供的crf是没问题的。您那边测试正常么？

**Comment by Tongjilibo** [comment]
> 我用这里的提供的crf，loss不收敛；但是用 [BERT_NER_Pytorch](https://github.com/lonePatient/BERT-NER-Pytorch/blob/master/models/layers/crf.py) 提供的crf是没问题的。您那边测试正常么？

您那边是用pip install包来调用的，还是git clone后直接调用的？刚刚排查发现git clone里面MultiAttn模块的softmax被我改错了，已经修复。
如果是使用git clone代码的，可以重新clone下，如果是pip install的，应该测试没啥问题，如果有问题提供下您的代码我看下

我的理解应该和CRF无关，我这边用的CRF是组里面很早有人就在用的，不过后续我会再验证下

**Comment by kangyishuai** [comment]
> 其实也只是代码风格的问题，主要是表示[START]转移到第一个token，以及最后一个token转移到[END]的转移，别的实现可能是单独实现的，并未表示成一整个转移矩阵，如[BERT-NER-Pytorch](https://github.com/lonePatient/BERT-NER-Pytorch/blob/master/models/layers/crf.py)中的start_transitions和end_transitions

对啊，是这个意思，哎，之前想了半天没想通，还是看的不够仔细，感谢感谢

**Comment by chironma** [comment]
> > 我用这里的提供的crf，loss不收敛；但是用 [BERT_NER_Pytorch](https://github.com/lonePatient/BERT-NER-Pytorch/blob/master/models/layers/crf.py) 提供的crf是没问题的。您那边测试正常么？
> 
> 您那边是用pip install包来调用的，还是git clone后直接调用的？刚刚排查发现git clone里面MultiAttn模块的softmax被我改错了，已经修复。 如果是使用git clone代码的，可以重新clone下，如果是pip install的，应该测试没啥问题，如果有问题提供下您的代码我看下
> 
> 我的理解应该和CRF无关，我这边用的CRF是组里面很早有人就在用的，不过后续我会再验证下

我是git clone后直接调用的，直接跑的examples中crf的例子，只是替换了数据集。我在clone试下看看把。

**Comment by Tongjilibo** [comment]
> 我是git clone后直接调用的，直接跑的examples中crf的例子，只是替换了数据集。我在clone试下看看把。

你这边有在尝试下吗？有发现还有问题吗？
