### ISSUE TITLE
您好，请问W2NER的预测怎么写呢

### ISSUE THREAD

**Issue by zyx214** [Tongjilibo/bert4torch#41]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Pytorch**版本: 
- 你使用的**bert4torch**版本: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
此处请贴上你的自我尝试过程

**Comment by Tongjilibo** [comment]
`decode()`中包含了预测的代码，需要把`convert_index_to_text()`改成把index转为你想要的entity的形式

**Comment by AnddyWang** [comment]
@Tongjilibo @zyx214 代码实现的W2NER模型有实验效果的对比么

**Comment by Tongjilibo** [comment]
> @Tongjilibo @zyx214 代码实现的W2NER模型有实验效果的对比么

可以参考 https://github.com/Tongjilibo/bert4torch/blob/master/examples/Performance.md
