### ISSUE TITLE
波哥， 请问运行运行W2NER在哪里下载bert4torch_pytorch_model.bin这个文件呀，用huggingface原版不行

### ISSUE THREAD

**Issue by H-miraitowa** [Tongjilibo/bert4torch#44]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Pytorch**版本: 
- 你使用的**bert4torch**版本: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
此处请贴上你的自我尝试过程

**Comment by Tongjilibo** [comment]
https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/convert_bert-base-chinese.py
