### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by lili-li-cpu** [Tongjilibo/bert4torch#45]
在关系抽取模型casrel中，如果在模型结构中加入了其他的网络结构，在def forward(self, inputs)中添加了使用过程。那么需要在class Model(BaseModel)下的def predict_subject(self, inputs)和def predict_object(self, inputs)下添加这个网络结构的使用嘛吗
![image](https://user-images.githubusercontent.com/66951248/195348242-f3a3e39d-6592-453d-89c8-bab53638f649.png)
![image](https://user-images.githubusercontent.com/66951248/195348275-a35f96d1-c9bb-4e15-a66b-f0a035d8d06e.png)
![image](https://user-images.githubusercontent.com/66951248/195348337-16c56764-36cd-4175-961a-75781e577fe4.png)

**Comment by Tongjilibo** [comment]
预测部分的代码大部分都是来自forward中的，如果你在forward中添加了新的网络结构，那预测时候一般也是需要的

**Comment by lili-li-cpu** [comment]
好的，明白了。谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月12日(星期三) 晚上9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tongjilibo/bert4torch] 一个小问题 (Issue #45)





 
预测部分的代码大部分都是来自forward中的，如果你在forward中添加了新的网络结构，那预测时候一般也是需要的
