### ISSUE TITLE
seq2seq_bart模型出错

### ISSUE THREAD

**Issue by wujindou** [Tongjilibo/bert4torch#46]
hi，我在使用您这边实现的bart的seq2seq模型时候，报错：__init__() missing 4 required positional 'hidden_size','num_attention_heads', 查看了下config问句确实是没有这些信息的，现在的bart模型地址：https://huggingface.co/fnlp/bart-base-chinese， 请问是不是框架还没有支持bart ？

**Comment by Tongjilibo** [comment]
https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/convert_bart_fudanNLP.py
