### ISSUE TITLE
大佬您好，看了您写的代码感觉非常棒，请问您后续打算用bert4torch复现CNN_Nested_NER么

### ISSUE THREAD

**Issue by 1365717822** [Tongjilibo/bert4torch#49]
附上https://github.com/yhcc/CNN_Nested_NER

**Comment by Tongjilibo** [comment]
您好，我简单看了下源代码，感觉实在roberta的last_hidden_states上加了额外的网络结构，从实现来看不是很难，我这边需求不是很强烈，所以安排的优先级不高。
建议如果你这边需求迫切的话，有兴趣的话也可以试试基于bert4torch二次开发，开发后可以提pull requests合并到bert4torch里面

**Comment by 1365717822** [comment]
好的，感谢您的回复！

**Comment by Tongjilibo** [comment]
您好，我这边修改了一下，在测试数据集上跑出了正常的指标~

**Comment by 1365717822** [comment]
好的，非常感谢您！
