### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by lili-li-cpu** [Tongjilibo/bert4torch#52]
collate_fn得到的batch集合  例如return [batch_token_ids, batch_segment_ids, batch_subject_ids, batch_attention_mask], [batch_subject_labels, batch_object_labels, batch_attention_mask]
它是怎么传入到模型中的呀

**Comment by Tongjilibo** [comment]
设定的是第一部分是模型forward需要的，第二部分是计算loss需要的label部分，因为我fit时候把dataloader传进去了，所以就能取到了，你可以断点调试看看每一步怎么走

**Comment by lili-li-cpu** [comment]
请问可以设置在模型结构中传嘛，比如这里







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月18日(星期二) 晚上7:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tongjilibo/bert4torch] 一个问题 (Issue #52)





 
设定的是第一部分是模型forward需要的，第二部分是计算loss需要的label部分，因为我fit时候把dataloader传进去了，所以就能取到了，你可以断点调试看看每一步怎么走

**Comment by Tongjilibo** [comment]
没看到你指向的内容

**Comment by lili-li-cpu** [comment]
![image](https://user-images.githubusercontent.com/66951248/196420223-9f0362dd-f80b-4238-b3c8-10d396fcbdfd.p就是self后面那里

**Comment by lili-li-cpu** [comment]
![@XL031 {JYZICSV6IC)W~ 1](https://user-images.githubusercontent.com/66951248/196420546-a777581f-9ae2-4e69-93f1-8ed59168c6c5.png)
就是画红色的那里

**Comment by lili-li-cpu** [comment]
就是可以在这里传入collate_fn生成的数据吗
