### ISSUE TITLE
作者您好，请问您以后会更新关系抽取例子中的代码对测试集的验证吗，我自己尝试去加，但能力不够

### ISSUE THREAD

**Issue by Liekkas22years** [Tongjilibo/bert4torch#53]
作者您好，请问您以后会更新关系抽取例子中的代码对测试集的验证吗，我自己尝试去加，但能力不够

**Comment by Tongjilibo** [comment]
我看了下关系抽取，三元组已经抽出来了，你说的测试集验证是指？

**Comment by Liekkas22years** [comment]
您好，我的意思是模型训练完，加载模型对测试集进行f1,p,r的计算，之前我看代码是训练过程对验证集进行的指标计算

**Comment by Liekkas22years** [comment]
大佬，能在task_relation_extraction_CasRel_VAT中写个样例吗

**Comment by Tongjilibo** [comment]
我在task_relation_extraction_CasRel中__main__下面增加了个读取并评估的，你看看是不是这种

```python
train_model.load_weights('best_model.pt')
f1, precision, recall = evaluate(valid_dataset.data)
```

**Comment by Liekkas22years** [comment]
我也是这样写的，我之前理解错了，谢谢大佬为我特地去加代码，衷心感谢！！！
