### ISSUE TITLE
用于英文数据应该改哪些？

### ISSUE THREAD

**Issue by XuJianzhi** [Tongjilibo/bert4torch#56]
波哥好。非常感谢做出bert4torch。
我想用于纯英文。我能想到就是转模型和tokenizer要改。

1、不知道tokenizer直接换成这种行不行？？（我倒是跑通了）

from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
..........
token_ids = tokenizer.encode(text)
segment_ids = [0 for _ in token_ids]      ## 文本分类，没有text_b

2、模型转换的这种对应关系是咋来的，我能自己写出来吗？

    if 'LayerNorm.gamma' in k:
        k = k.replace('LayerNorm.gamma', 'LayerNorm.weight')
        state_dict_new[k] = v

（我自己试的结果是bert-base-uncased能用bert-base-chinese的转换文件，上述方法貌似ok，，不知道转其他模型的对应关系应该如何写出。）

**Comment by Tongjilibo** [comment]
1、换成英文的可以使用transformer自带的tokenizer的
2、可以自己写，对应关系其实你用torch.load()就得到的一个key,value的字典，你打印出来，把两边的key映射关系整理好就可以了自己写映射就行
