### ISSUE TITLE
关系抽取

### ISSUE THREAD

**Issue by Superxiaoxin-522** [Tongjilibo/bert4torch#57]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: ubuntu
- 你使用的**Python**版本: 3.7
- 你使用的**Pytorch**版本: 1.10
- 你使用的**bert4torch**版本: 0.2.3
- 你加载的**预训练模型**:nezha

### 核心代码
```python
# 请在此处贴上你的核心代码
```
![image](https://user-images.githubusercontent.com/84958267/197996621-73665ecb-a6b5-4826-ab6b-3d880190db8a.png)

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
![image](https://user-images.githubusercontent.com/84958267/197996068-5e1afea6-31d0-49c2-8197-c90cd249c353.png)
![1666778113296](https://user-images.githubusercontent.com/84958267/197996188-8bf58233-fbec-46fa-8cc3-869eaf7d4cea.png)

### 自我尝试
此处请贴上你的自我尝试过程
为什么关系抽取代码，仅将加载数据的代码改动，第一个epoch推理速度这么慢呢？我将数据换回百度的依然如此，希望能解答一下

**Comment by Tongjilibo** [comment]
我的代码直接跑第一个epoch会这样吗？如果不是，能否提供下你的脚本、发邮箱也可以

**Comment by Superxiaoxin-522** [comment]
你好，博主，冒昧打扰了。我发了一份压缩文件，其中re_bdci.py是我的项目文件，我仅做了数据加载的改动，同时我也换回了源代码进行了百度数据的实验也如图所示。不知道是哪里出了问题。里面的dev,train.json是我任务的数据集，对应的代码块也注释掉了

**Comment by Tongjilibo** [comment]
您好，我的邮箱没收到你的邮件，您是发哪里了啊

**Comment by Tongjilibo** [comment]
我这里用百度的数据集结果如下（为了节约时间每个epoch只跑了100步），没有出现第一个epoch的evaluate耗时过长的问题啊
<img width="799" alt="Snipaste_2022-10-26_23-08-21" src="https://user-images.githubusercontent.com/33407736/198064905-18c77e2b-43ab-403b-b468-650a67bca1d8.png">
