### ISSUE TITLE
task_sequence_labeling_ner_CNN_Nested_NER运行问题

### ISSUE THREAD

**Issue by QAQ112** [Tongjilibo/bert4torch#60]
大佬您好，在最近运行您于几日前上传的task_sequence_labeling_ner_CNN_Nested_NER模型时，发现其运行结果的[val-entity level]如下 f1: 0.00012, p: 0.00006 r: 0.08758 best_f1: [0.00012，运行多个epoch以后发现结果仍不理想，麻烦大佬百忙之中抽空回答一下。
(https://user-images.githubusercontent.com/91443497/198867006-f91ac386-5b54-48e3-aadd-b9bdefaf4d4e.png)

**Comment by Tongjilibo** [comment]
您好，是的，我这个还没完成还在调整中，如果你有发现bug也可以帮忙看下

**Comment by QAQ112** [comment]
好的，感谢您的回复！

**Comment by Tongjilibo** [comment]
您好，我这边修改了一下，在测试数据集上跑出了正常的指标~
