### ISSUE TITLE
关于xlnet的分词器问题

### ISSUE THREAD

**Issue by QAQ112** [Tongjilibo/bert4torch#61]
最近在尝试将xlnet与bert用于ner并对两者进行比较，在您开源的bert+crf模型（task_sequence_labeling_ner_crf.py）基础上将bert替换成xlnet后，将预训练权重与分词器Tokenizer替换成SpTokenizer后，发现原本的tokens划分有的从单个字变成了两个字，因此在程序运行后出现TypeError: rematch() takes 1 positional argument but 3 were given 的错误 ，请问大佬这个问题出在哪里呢？麻烦大佬百忙中抽空解答一下。

**Comment by Tongjilibo** [comment]
您好，我这边看了下bert4keras的实现，其中对于SpTokenizer并没有rematch这个方法实现，我这里因为把rematch放到基类里面，但是继承后并未实现，所以提示如上错误，后续我看下是否有实现的可能性，也欢迎您一起探讨和实现

**Comment by Tongjilibo** [comment]
您好，我的理解是中文sentence piece不太适合做序列标注任务，分词可能有实体标记冲突，即使训练时候可以强行把实体部分单独拎出来，但是预测阶段分词还是会出问题

**Comment by QAQ112** [comment]
大佬你好，我找到了有关xlnet-bilstm-crf用于中文命名实体识别的代码复现，发现他提供的代码在dataload.py中的def collate_fn这个函数上的处理比你的简单很多，由于我所使用的GPU显存过小无法运行，他这样的处理是不是您所说的强行将实体部分单独拎出来？

代码地址：https://gitee.com/obolicaca/Medical_NER#%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B

**Comment by Tongjilibo** [comment]
你可以仔细看下他的feature.py，并没有使用XlnetTokenizer，而是字典直接映射的

**Comment by QAQ112** [comment]
好的

**Comment by Tongjilibo** [comment]
刚刚只是讨论分词的问题哈，真的要训xlnet，你也可以参考上面的做法直接token_to_id
