### ISSUE TITLE
大佬您好，我想问一下roberta的mlm预训练的数据长什么样

### ISSUE THREAD

**Issue by swx-10** [Tongjilibo/bert4torch#63]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: win
- 你使用的**Python**版本: 3.8
- 你使用的**Pytorch**版本: 1.7
- 你使用的**bert4torch**版本: 0.2.0
- 你加载的**预训练模型**:roformer

**Comment by Tongjilibo** [comment]
您好，我这边使用的是一个文件夹里面有很多txt文件，每个txt文件很多行，每行表示一句话，如下所示
```text
百度百科是百度公司推出的一部内容开放、自由的网络百科全书平台。其测试版于2006年4月20日上线，正式版在2008年4月21日发布，截至2016年4月，百度百科已经收录了超过1300多万的词条，参与词条编辑的网友超过580万人，几乎涵盖了所有已知的知识领域。百度百科旨在创造一个涵盖各领域知识的中文信息收集平台。百度百科强调用户的参与和奉献精神，充分调动互联网用户的力量，汇聚上亿用户的头脑智慧，积极进行交流和分享。同时，百度百科实现与百度搜索、百度知道的结合，从不同的层次上满足用户对信息的需求。
馒头，又称之为馍、蒸馍 ，中国特色传统面食之一，一种用面粉发酵蒸成的食品，形圆而隆起。本有馅，后称无馅的为馒头，有馅的为包子。通常北方人们选择馒头来作为主食。据传是三国时期诸葛亮发明。《三国演义》中讲述诸葛亮七擒孟获，平定南蛮之后，过江受战死冤魂之阻。诸葛亮面对此景心急如焚，想来想去只好祭奠河神，求神降福惩魔，保佑生灵，诸葛亮不忍用人头祭祀，而发明馒头为替代品。于是命杀羊宰猪，包成面团，投于水中以示供奉。后来民间习此风俗。这大概是“馒头”的起源。“馒”通“蛮”，“馒头”即意为“蛮头”。馒头把面粉加水、糖等调匀，发酵后蒸熟而成的食品，成品外形为半球形或长条。在江南地区，在制作时加入肉、菜、豆蓉等馅料的此类面食都通通叫做馒头，而无馅的馒头叫白馒头。味道可口松软，营养丰富，是餐桌上必不可少的主食之一。中国幅员辽阔，民族众多，口味不同，作法各异，由此发展出了各式各样的馒头，如白面馒头，玉米面馒头、菜馒头、肉馒头、生煎馒头、油炸馒头，叫法也不尽相同，馒头是中国北方的主食。
雁荡山以山水奇秀闻名，素有“海上名山、寰中绝胜”之誉，史称中国“东南第一山” ，主体位于浙江省温州市东北部海滨，小部在台州市温岭南境。雁荡山形成于一亿二千万年以前，是环太平洋大陆边缘火山带中一座日至纪流纹质破火地。《载敬堂集》载：“雁荡山以瓯江自然断裂，分北雁荡山和南雁荡山。以景观区位分有北雁荡山、南雁荡山、西雁荡山、东雁荡山、中雁荡山之称。”其开山凿胜始于南北朝，兴于唐，盛于宋。历代文人墨客纷至沓来，谢灵运、沈括、徐霞客、张大千、郭沫若等都留下了诗篇和墨迹。
灵峰为雁荡山的东大门景区，总面积约46平方公里。以悬崖叠嶂，奇峰怪石，古怪石室，碧潭清润而著称。与灵岩、大龙湫并称为雁荡三绝。景区内层峦叠嶂，奇峰环绕，千形万状，美不胜收。灵峰夜景，移步换形，变幻多姿，妙不可言。两大奇洞——观音洞、北斗洞为游人所必至。合掌峰是雁荡山的代表景观之一。
雁荡山景区分散，东起羊角洞，西至锯板岭；南起筋竹溪，北至六坪山。在方圆450平方公里的景区内，东西阔28公里，南北长7.5公里，面积为28平方公里。其中有15峰、13岩、7石、5嶂、6洞、1尖、3门、2阙、8岭、5瀑、2湫、8潭、1泉、3溪、2涧、1峡、4庵、7亭、1院、1镬、1轩、2桥，合计景点105个。共分为灵峰、灵岩、大龙湫、显胜门、仙桥、羊角洞、净名三折瀑、雁湖八大景区，而东南部地区最称风景荟萃。其中“二灵一龙”即灵峰、灵岩和大龙湫又被称为“雁荡三绝”，大龙湫在三绝中又被认为是独占鳌头。南宋楼钥有诗云：“北上太行东禹穴，雁荡山中最奇绝。龙湫一派天下无，万众赞扬同一舌。”（《攻瑰集·大龙湫》）可见在宋代，大龙湫便已扬四海。

```

**Comment by swx-10** [comment]
> 您好，我这边使用的是一个文件夹里面有很多txt文件，每个txt文件很多行，每行表示一句话，如下所示
> 
> ```
> 百度百科是百度公司推出的一部内容开放、自由的网络百科全书平台。其测试版于2006年4月20日上线，正式版在2008年4月21日发布，截至2016年4月，百度百科已经收录了超过1300多万的词条，参与词条编辑的网友超过580万人，几乎涵盖了所有已知的知识领域。百度百科旨在创造一个涵盖各领域知识的中文信息收集平台。百度百科强调用户的参与和奉献精神，充分调动互联网用户的力量，汇聚上亿用户的头脑智慧，积极进行交流和分享。同时，百度百科实现与百度搜索、百度知道的结合，从不同的层次上满足用户对信息的需求。
> 馒头，又称之为馍、蒸馍 ，中国特色传统面食之一，一种用面粉发酵蒸成的食品，形圆而隆起。本有馅，后称无馅的为馒头，有馅的为包子。通常北方人们选择馒头来作为主食。据传是三国时期诸葛亮发明。《三国演义》中讲述诸葛亮七擒孟获，平定南蛮之后，过江受战死冤魂之阻。诸葛亮面对此景心急如焚，想来想去只好祭奠河神，求神降福惩魔，保佑生灵，诸葛亮不忍用人头祭祀，而发明馒头为替代品。于是命杀羊宰猪，包成面团，投于水中以示供奉。后来民间习此风俗。这大概是“馒头”的起源。“馒”通“蛮”，“馒头”即意为“蛮头”。馒头把面粉加水、糖等调匀，发酵后蒸熟而成的食品，成品外形为半球形或长条。在江南地区，在制作时加入肉、菜、豆蓉等馅料的此类面食都通通叫做馒头，而无馅的馒头叫白馒头。味道可口松软，营养丰富，是餐桌上必不可少的主食之一。中国幅员辽阔，民族众多，口味不同，作法各异，由此发展出了各式各样的馒头，如白面馒头，玉米面馒头、菜馒头、肉馒头、生煎馒头、油炸馒头，叫法也不尽相同，馒头是中国北方的主食。
> 雁荡山以山水奇秀闻名，素有“海上名山、寰中绝胜”之誉，史称中国“东南第一山” ，主体位于浙江省温州市东北部海滨，小部在台州市温岭南境。雁荡山形成于一亿二千万年以前，是环太平洋大陆边缘火山带中一座日至纪流纹质破火地。《载敬堂集》载：“雁荡山以瓯江自然断裂，分北雁荡山和南雁荡山。以景观区位分有北雁荡山、南雁荡山、西雁荡山、东雁荡山、中雁荡山之称。”其开山凿胜始于南北朝，兴于唐，盛于宋。历代文人墨客纷至沓来，谢灵运、沈括、徐霞客、张大千、郭沫若等都留下了诗篇和墨迹。
> 灵峰为雁荡山的东大门景区，总面积约46平方公里。以悬崖叠嶂，奇峰怪石，古怪石室，碧潭清润而著称。与灵岩、大龙湫并称为雁荡三绝。景区内层峦叠嶂，奇峰环绕，千形万状，美不胜收。灵峰夜景，移步换形，变幻多姿，妙不可言。两大奇洞——观音洞、北斗洞为游人所必至。合掌峰是雁荡山的代表景观之一。
> 雁荡山景区分散，东起羊角洞，西至锯板岭；南起筋竹溪，北至六坪山。在方圆450平方公里的景区内，东西阔28公里，南北长7.5公里，面积为28平方公里。其中有15峰、13岩、7石、5嶂、6洞、1尖、3门、2阙、8岭、5瀑、2湫、8潭、1泉、3溪、2涧、1峡、4庵、7亭、1院、1镬、1轩、2桥，合计景点105个。共分为灵峰、灵岩、大龙湫、显胜门、仙桥、羊角洞、净名三折瀑、雁湖八大景区，而东南部地区最称风景荟萃。其中“二灵一龙”即灵峰、灵岩和大龙湫又被称为“雁荡三绝”，大龙湫在三绝中又被认为是独占鳌头。南宋楼钥有诗云：“北上太行东禹穴，雁荡山中最奇绝。龙湫一派天下无，万众赞扬同一舌。”（《攻瑰集·大龙湫》）可见在宋代，大龙湫便已扬四海。
> ```

只需要文本的txt就行吗，那个robert预训练的代码会报错

**Comment by Tongjilibo** [comment]
贴下报错代码

**Comment by swx-10** [comment]
文件夹里面是txt的话，会直接No training data! Sleep 300s!

**Comment by swx-10** [comment]
因此我觉得是不是我数据搞错了，需要特殊处理还是啥，所以，过来问问大佬

**Comment by Tongjilibo** [comment]
我给的代码一个是数据生成一个是训练，是同时运行的，你先把数据生成的跑起来会看到有数据生成出来，然后训练代码中路径要指向生成出来的数据，是边生成数据边训练的过程

**Comment by swx-10** [comment]
哦哦，原来如此，感谢！

**Comment by swx-10** [comment]
在model.complie()那个地方报了一个compile() got an unexpected keyword argument 'grad_accumulation_steps'错误。
![1668058873701](https://user-images.githubusercontent.com/81468192/201009792-ecdeb400-13d7-4ea8-82fe-3e95d67d097d.jpg)

**Comment by swx-10** [comment]
> 在model.complie()那个地方报了一个compile() got an unexpected keyword argument 'grad_accumulation_steps'错误。 ![1668058873701](https://user-images.githubusercontent.com/81468192/201009792-ecdeb400-13d7-4ea8-82fe-3e95d67d097d.jpg)

去除该参数后，可正常训练，现在是不支持这个参数了吗？

**Comment by Tongjilibo** [comment]
升级到最新版本试试？

**Comment by swx-10** [comment]
从v0.2.2升到v0.2.3版本后，问题解决。感谢！
