### ISSUE TITLE
请问UIE模型的bin文件在哪里下载的

### ISSUE THREAD

**Issue by YLiberals** [Tongjilibo/bert4torch#65]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Pytorch**版本: 
- 你使用的**bert4torch**版本: 
- 你加载的**预训练模型**:

### 核心代码
```python
# 请在此处贴上你的核心代码
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
此处请贴上你的自我尝试过程

**Comment by Tongjilibo** [comment]
直接运行uie/convert.py文件就可以自动下载并转成pytorch格式的了

**Comment by YLiberals** [comment]
> 直接运行uie/convert.py文件就可以自动下载并转成pytorch格式的了

谢谢！
