### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by lili-li-cpu** [Tongjilibo/bert4torch#69]
提问时请尽可能提供如下信息：
![image](https://user-images.githubusercontent.com/66951248/202379737-f16dac25-e07a-43dc-8bda-c67e3f6293e6.png)

**Comment by lili-li-cpu** [comment]
像前面300多轮都没有问题，再361轮的时候出现了错误（关系抽取vat版本代码）

**Comment by Tongjilibo** [comment]
跑300多轮花了多久？我看看我这能不能复现出来

**Comment by lili-li-cpu** [comment]
7个小时左右




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月17日(星期四) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tongjilibo/bert4torch] 问题 (Issue #69)





 
跑300多轮花了多久？我看看我这能不能复现出来

**Comment by Tongjilibo** [comment]
我这边看下，我猜测和随机种子没啥关系，出错都是next()这句，而且都是最后一个batch

**Comment by lili-li-cpu** [comment]
好的好的，我也检查了我的数据文本，没有空行的

**Comment by Tongjilibo** [comment]
我大概猜到是哪里的问题了，应该是碰巧`collate_fn`中整个batch的`if spoes`都没有进，所以`batch_subject_labels`只是一个空数组，因此导致这个问题

**Comment by lili-li-cpu** [comment]
那这种情况应该怎么处理呢，他每到300多轮就卡住了，应该不是数据的问题吧

**Comment by Tongjilibo** [comment]
我看你close了，是没有这个问题了是吗？

**Comment by lili-li-cpu** [comment]
嗷嗷，我试了一下，经过那个解析样本以后，我的一部分不符合的数据被清掉了，然后跑了很多轮也没有出现问题。非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 下午5:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Tongjilibo/bert4torch] 问题 (Issue #69)





 
我看你close了，是没有这个问题了是吗？
