### ISSUE TITLE
关于torch版本

### ISSUE THREAD

**Issue by 1973719588** [Tongjilibo/bert4torch#7]
请问torch版本应该选择多少？

**Comment by Tongjilibo** [comment]
你有遇到不适配的情况吗？大部分功能应该1.几都可以，我自己开发使用的是1.10

**Comment by 1973719588** [comment]
torch1.8.0不太合适，torch.take_along_dim()这个包找不到。最后我也换到1.10.0就跑通了。

**Comment by Tongjilibo** [comment]
> torch1.8.0不太合适，torch.take_along_dim()这个包找不到。最后我也换到1.10.0就跑通了。

好的，谢谢反馈，我这边在readme中更新一下
