### ISSUE TITLE
请问如何用roformer-sim来实现相似句二分类任务啊

### ISSUE THREAD

**Issue by aph-asic** [Tongjilibo/bert4torch#71]
![image](https://user-images.githubusercontent.com/54587975/202653606-7f590163-e15b-4732-909b-a6efa72888fa.png)

**Comment by aph-asic** [comment]
![image](https://user-images.githubusercontent.com/54587975/202661753-9507636a-f504-4b83-9367-2f1aa9296c2d.png)
请问是这样写吗

**Comment by Tongjilibo** [comment]
你说的应该不是走句向量相似度（表示型）的方式，应该是说走分类任务（交互型）？样本就是 sent1和sent2拼接起来，那就是第二张图的做法

**Comment by aph-asic** [comment]
是输入两句文本，然后做二分类判断语义是否相似，是用第二种对吧。谢谢您的说明

**Comment by Tongjilibo** [comment]
> 是输入两句文本，然后做二分类判断语义是否相似，是用第二种对吧。谢谢您的说明

你是要finetune还是直接调用预训练模型出结果啊？我的理解你是要finetune是吗？如果是走相似度方案那就要得到句向量，就不是我刚说的方案

**Comment by aph-asic** [comment]
我用的是roformer-sim来finetune，主要就是照着苏老师在sohu2021文本相似度任务方案改的，输入的就是拼接的两个文本和标签
![image](https://user-images.githubusercontent.com/54587975/202671969-3c92e6ff-ab8b-47ee-981d-90fddb366fa0.png)

**Comment by aph-asic** [comment]
![image](https://user-images.githubusercontent.com/54587975/202672926-5d1035d1-9a1e-48ac-8884-b3945169c938.png)
模型的训练是这样的

**Comment by Tongjilibo** [comment]
那应该可以

**Comment by aph-asic** [comment]
好的，谢谢您的指导
