### ISSUE TITLE
task_sequence_labeling_ner_tplinker_plus报错，f1为0

### ISSUE THREAD

**Issue by LiangXD** [Tongjilibo/bert4torch#73]
![image](https://user-images.githubusercontent.com/29204038/202901554-d0c0c9a7-4086-4af2-bccd-7fce30aa9d10.png)

**Comment by Tongjilibo** [comment]
您好，我这边重新跑了这个示例，
![image](https://user-images.githubusercontent.com/33407736/202903352-69a6f5fb-4ec0-47b5-84d3-0a0afad6eb9f.png)

**Comment by LiangXD** [comment]
你好，我pip安装的bert4torch==0.2.3，torch=1.10.0，python是3.7的，在Windows下跑的，我debug看了一下evaluate函数，预测出来的scores都是小于threshold的，不知道怎么回事了。

**Comment by LiangXD** [comment]
> 您好，我这边重新跑了这个示例， ![image](https://user-images.githubusercontent.com/33407736/202903352-69a6f5fb-4ec0-47b5-84d3-0a0afad6eb9f.png)

你好，我pip安装的bert4torch==0.2.3，torch=1.10.0，python是3.7的，在Windows下跑的，我debug看了一下evaluate函数，预测出来的scores都是小于threshold的，不知道怎么回事了。

**Comment by Tongjilibo** [comment]
有报warning吗？先确认下预训练权重是否正常加载

**Comment by LiangXD** [comment]
> 有报warning吗？先确认下预训练权重是否正常加载

刚开始是有warning，LayerNorm.weight和LayerNorm.bias找不到，后面用[github](https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/convert_bert-base-chinese.py)转换脚本权重，并且config也用这网站里面的替换了，还是f1为0

**Comment by Tongjilibo** [comment]
那是有点奇怪了，截图中是我跑的结果，我跑了前几个epoch，应该是正常的

**Comment by LiangXD** [comment]
> 那是有点奇怪了，截图中是我跑的结果，我跑了前几个epoch，应该是正常的

我是用Windows跑的，应该没有关系吧

**Comment by Tongjilibo** [comment]
没关系，我本机和服务器都跑了，f1都有值，你是直接修改模型路径和数据路径，跑的我的脚本是吧？

**Comment by LiangXD** [comment]
> 没关系，我本机和服务器都跑了，f1都有值，你是直接修改模型路径和数据路径，跑的我的脚本是吧？

对的，只改了模型路径和数据路径
![image](https://user-images.githubusercontent.com/29204038/202910797-8a31385d-4a1c-492b-9625-dcad917ccc45.png)
![image](https://user-images.githubusercontent.com/29204038/202910808-2114e338-412d-41a1-b684-5361d136bee1.png)

**Comment by Tongjilibo** [comment]
你先排查下，最后不行再发我下你的代码试试，或者你换个预训练模型看下

**Comment by LiangXD** [comment]
> 你先排查下，最后不行再发我下你的代码试试，或者你换个预训练模型看下

换了哈工大的预训练模型，还是没找到哪里的问题，感觉是model.predict的问题，预测的predict全部是这种
![image](https://user-images.githubusercontent.com/29204038/202963158-7ba67166-e6b1-44ef-b828-f074a1fa0a82.png)

**Comment by Tongjilibo** [comment]
你加下我微信Tongjilibo，晚上我看下？

**Comment by Tongjilibo** [comment]
我这里测试没问题，如果有问题再反馈
