### ISSUE TITLE
预测速度问题

### ISSUE THREAD

**Issue by wfs420100** [Tongjilibo/bert4torch#75]
您好，请问uie改写为torch后的预测速度和paddlepaddle官方实现的有差吗

**Comment by wfs420100** [comment]
我这边还没有开始，就想问问推理速度对比情况，如果torch较慢的话（paddle内部有加速处理）就使用paddle了。但是paddlepaddle在当前的线上服务部署起来有点麻烦（当前公司的线上环境问题）

**Comment by Tongjilibo** [comment]
看你怎么部署？torch也可以走onnx, tensorrt，tyrion 等方案
