### ISSUE TITLE
预训练模型加载

### ISSUE THREAD

**Issue by 447428054** [Tongjilibo/bert4torch#76]
提问时请尽可能提供如下信息：
@Tongjilibo 请问通过提供的预训练脚本训练出来的模型，如何转成可以被别的模型加载的格式呢，我用其他模型【uie】尝试加载后提示缺少参数，如何只加载双方都有的参数呢

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 
- 你使用的**Pytorch**版本: 
- 你使用的**bert4torch**版本: 
- 你加载的**预训练模型**:

预训练的模型是这样的：model = build_transformer_model(config_path, checkpoint_path, with_mlm=True).to(device)

想要加载的是uie模型
uie_model = build_transformer_model(config_path=config_path, checkpoint_path=checkpoint_path, model=UIE, with_pool=True)

### 核心代码
```python
# 请在此处贴上你的核心代码
```
uie_model.load_weights('xx/model/bert_model.ckpt')

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
RuntimeError: Error(s) in loading state_dict for UIE:
	Missing key(s) in state_dict: "embeddings.task_type_embeddings.weight", "pooler.weight", "pooler.bias", "linear_start.weight", "linear_start.bias", "linear_end.weight", "linear_end.bias". 
	Unexpected key(s) in state_dict: "mlmBias", "mlmDense.weight", "mlmDense.bias", "mlmLayerNorm.weight", "mlmLayerNorm.bias", "mlmDecoder.weight", "mlmDecoder.bias". 

### 自我尝试
此处请贴上你的自我尝试过程

**Comment by Tongjilibo** [comment]
你是说通过bert4torch预训练得到模型，希望通过build_transformer_model来加载是吗？还是说预训练得到的模型用别的框架来加载？没有特别明白你说的意思

**Comment by 447428054** [comment]
> 

我是用pretrain_roberta_mlm.py这个脚本进行继续预训练的哈，模型选择的是uie

然后想要用uie加载继续预训练后的模型，发现了上述的报错，看上去是uie里面的线性层在MLM里面没有，同时MLM的dense层uie也没有，想的是怎么加载两个模型公有的参数部分呢

**Comment by Tongjilibo** [comment]
我周末试一下

**Comment by Tongjilibo** [comment]
我这边测试后结论如下，如果在`pretrain_roberta_mlm.py`中保存模型时候使用`model.save_weights(model_saved_path, prefix='')`，则在UIE中加载`uie_model = build_transformer_model(config_path=config_path, checkpoint_path=checkpoint_path, model=UIE, with_pool=True)`中会提示如下
```text
[WARNIMG] bert.embeddings.token_type_embeddings.weight not found in pretrain models
[WARNIMG] bert.pooler.dense.weight not found in pretrain models
[WARNIMG] bert.pooler.dense.bias not found in pretrain models
[WARNIMG] linear_start.weight not found in pretrain models
[WARNIMG] linear_start.bias not found in pretrain models
[WARNIMG] linear_end.weight not found in pretrain models
[WARNIMG] linear_end.bias not found in pretrain models
```
这样应该就是你说的加载了模型公共的部分

**Comment by 447428054** [comment]
> 

您好，十分感谢，我试了一下哈，但是这样就导致UIE里面的线性层权重没有加载了，在后续应用的效果更差了

**Comment by Tongjilibo** [comment]
> > 
> 
> 您好，十分感谢，我试了一下哈，但是这样就导致UIE里面的线性层权重没有加载了，在后续应用的效果更差了

我的理解也是会更差，个人理解要预训练也是用uie去做预训练，然后再加载后来微调吧

**Comment by 447428054** [comment]
> 

我刚刚继续看了一下，load_state_dict里面strict置为false能够实现要的功能，uie与bert预训练的公共部分加载

**Comment by Tongjilibo** [comment]
你的意思是先加载uie的权重，然后再加载你预训练权重的公共部分？执行上是可以的，但是效果还要你测试下。
另外报这个warning是我手动触发的，防止未成功加载却不知道原因，你直接用load_state_dict(strict=false)是可以的，其实我内部实现也是这样的
