### ISSUE TITLE
请问可以加载WoBERT模型吗？

### ISSUE THREAD

**Issue by coder-duibai** [Tongjilibo/bert4torch#78]
你好，请问可以加载WoBERT模型吗？

**Comment by Tongjilibo** [comment]
我看下，追一的wobert是在哈工大开源的[RoBERTa-wwm-ext](https://github.com/ymcui/Chinese-BERT-wwm)基础上进行继续预训练的，我这边适配下~

**Comment by coder-duibai** [comment]
你好，我看了一下代码，是微调用的，请问有预训练的代码吗？

**Comment by Tongjilibo** [comment]
Wobert预训练的代码吗？目前还没有

**Comment by coder-duibai** [comment]
你好，请问一下，Wobert的keras版本预训练代码如果想改成pytorch版本，请问该怎么改呢，能给点思路和指导吗，谢谢！

**Comment by Tongjilibo** [comment]
我的理解是把corpus()改为bert4torch中ListDataset的load_data(), data_generator改为collate_fn并对train的dev分别组成dataloader，模型部分保持一致，计算loss部分参考着改一下，梯度累积直接在compile中设置grad_accumulation_steps参数，其他没什么特别的了
