### ISSUE TITLE
多分类任务

### ISSUE THREAD

**Issue by kakanixiya** [Tongjilibo/bert4torch#79]
您好，请问多分类任务应该修改哪些参数呢，我在例子中没有看到，谢谢

**Comment by Tongjilibo** [comment]
文本分类任务中把nn.Linear()把2改成多分类个数应该就可以了吧

**Comment by kakanixiya** [comment]
哦哦，我以为您封装好修改参数了，我今天刚发现这个框架还没仔细看里面的模型&nbsp; 十分感谢您的回复！&nbsp;


不爱名利，你至上
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月18日(星期天) 晚上10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tongjilibo/bert4torch] 多分类任务 (Issue #79)





 
文本分类任务中把nn.Linear()把2改成多分类个数应该就可以了吧

**Comment by Tongjilibo** [comment]
好的，欢迎试用~
