### ISSUE TITLE
关于simbert的模型的咨询

### ISSUE THREAD

**Issue by xdg2016** [Tongjilibo/bert4torch#80]
请问，追一科技的simbert的torch模型您是直接转成pytorch的呢？还是重新用bert4torch训练得到的呢？
其他的两个模型：small和tiny有没有计划实现呢？
![image](https://user-images.githubusercontent.com/16351823/208405343-a63c32dd-ff95-4600-b2b7-3c98bcb1ffdb.png)

**Comment by Tongjilibo** [comment]
你好，是用的别人转好的，这是simbert base的[链接](https://huggingface.co/peterchou/simbert-chinese-base/tree/main)，当然转应该也不麻烦，你可以自行转small和tiny的，后续我也可以提供转换脚本

**Comment by xdg2016** [comment]
谢谢，我试着转了small和tiny的模型，转出来运行有问题，折腾了挺久，还是不行，您这边方便的话，我参考一下您的转换脚本，谢谢了

**Comment by Tongjilibo** [comment]
[转换脚本](https://github.com/Tongjilibo/bert4torch/blob/master/examples/convert_script/convert_simbert.py), [调用脚本](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_simbert.py)，用上述脚本试下看看，如果没问题欢迎star

**Comment by Tongjilibo** [comment]
对了，请使用最新的git上的bert4torch，以及torch4keras==0.0.5版本

**Comment by xdg2016** [comment]
谢谢，我这边根据您的脚本转换成功了，而且可以按照示例脚本可以成功运行，但是我在重新保存模型的时候出错了：
![image](https://user-images.githubusercontent.com/16351823/208611638-2848677d-dc26-4e3d-bb0b-bf9ad8c9196b.png)
麻烦您看一下

**Comment by Tongjilibo** [comment]
input_data1和input_data2传入torch.long类型的试一下

**Comment by xdg2016** [comment]
可以了，这两个数据类型没改，改完就可以了
另外，我也转了small和tiny两个模型，转完的权重文件重新用basic_language_model_simbert.py读取，又存在维度不匹配的错误：
![image](https://user-images.githubusercontent.com/16351823/208623460-475b6522-c503-4d64-8104-332a0f8124d9.png)

**Comment by Tongjilibo** [comment]
用github上的bert4torch，不要使用pip install的版本

**Comment by xdg2016** [comment]
厉害了我的哥，三个模型都可以转成功了，果断star，谢谢！
