### ISSUE TITLE
simbert测试疑惑

### ISSUE THREAD

**Issue by xdg2016** [Tongjilibo/bert4torch#82]
您好，我这边下载了别人训练好的权重
![image](https://user-images.githubusercontent.com/16351823/208838501-68132df1-b165-4e26-bc8f-6f7e1d48abd5.png)
做文本相似度的测试：
![image](https://user-images.githubusercontent.com/16351823/208838415-b20ce316-f860-4638-93bc-aa4be283755d.png)
测试结果;
cos_sim: 0.7136, tgt_text: "今天晚上加班", cal_text: "吃了苹果会拉肚子"
这两句意思差距很大，相似度却有0.70+，此外我按照您的转换脚本转换了原作者的keras权重，得到的相似度一模一样也是0.7136
这个相似度是不是不太合理呀，同样的模型，我测试了paddlenlp的taskflow中的simbert_base_chinese模型，相同的两个句子，相似度只有：0.040254187
感觉paddlenlp中的更合理一点

**Comment by Tongjilibo** [comment]
你可以用苏神的bert4keras试下，看看相似度和我的框架一致吗？如果一致那说明bert4torch没啥问题，是预训练模型的问题，如果不一致，那就是我这边的问题

**Comment by xdg2016** [comment]
您好，我这边试了一下，苏神的结果和paddlenlp的结果一致，
您的模型结果：
cos_sim: 0.7136, tgt_text: "今天晚上加班", cal_text: "吃了苹果会拉肚子"
cos_sim: 0.7484831213951111, tgt_text: "地球是圆的", cal_text: "这张纸真难用"
苏神的结果：
data = [("今天晚上加班","吃了苹果会拉肚子",0),("地球是圆的","这张纸真难用",0)]
![image](https://user-images.githubusercontent.com/16351823/208850947-70dd628e-5c4a-43b9-ade8-e1d6e8e9ae49.png)
paddlenlp的结果;
simi: 0.04025418683886528 text1:今天晚上加班 text2: 吃了苹果会拉肚子
simi: 0.07550185918807983 text1:地球是圆的 text2: 这张纸真难用

从结果来看，苏神和paddlenlp的结果一致，且符合语义。
我对比了输入，应该是您这边tokenizer部分对词表做了精简，大小变成了13584，而苏神那边的tokenizer和paddlenlp的一样，都是13685，您看一下

**Comment by xdg2016** [comment]
我这边经过测试，paddlenlp和苏神用于计算相似度的向量都是取bert的输出，也就是您代码中的pooler结果
![image](https://user-images.githubusercontent.com/16351823/208854516-728223a2-c88c-4e68-8cdc-4a72ea83d60f.png)
取pooler结果做相似度计算就和苏神的一样了。

**Comment by Tongjilibo** [comment]
好的，那应该就是`pool_method`需要传入`pool_method='pooler'`

**Comment by xdg2016** [comment]
是的，修改完一致了，谢谢

**Comment by Tongjilibo** [comment]
好的，我也修改了下，谢谢
