### ISSUE TITLE
xlnet tokenize

### ISSUE THREAD

**Issue by huaweiboy** [Tongjilibo/bert4torch#83]
![image](https://user-images.githubusercontent.com/5070286/208934512-9de41eed-b9f4-41c2-aab3-686bc26dd50e.png)
佬，这里tokenize的结果貌似是 X[cls] 而不是 X[seq][cls]
![image](https://user-images.githubusercontent.com/5070286/208934774-d8be3398-de22-49c1-87df-73c052d2134b.png)

**Comment by Tongjilibo** [comment]
谢谢，是有这样的问题，我进行了修复，并且xlnet的padding应该都是padding在前面的，所以模型部分也修改了下，您可以看一下
