### ISSUE TITLE
task_sentiment_virtual_adversarial_training.py 是不是缺点东西？

### ISSUE THREAD

**Issue by XuJianzhi** [Tongjilibo/bert4torch#85]
https://github.com/Tongjilibo/bert4torch/blob/master/examples/training_trick/task_sentiment_virtual_adversarial_training.py#L127 是不是应该从

adversarial_train = AdversarialTraining('vat', adversarial={'adv_alpha': 1})  # 虚拟对抗
model.fit(train_dataloader, epochs=10, steps_per_epoch=None, callbacks=[evaluator])

改为

model.fit(train_dataloader, epochs=10, steps_per_epoch=None, callbacks=[evaluator, adversarial_train ])

因为，貌似 adversarial_train 没用上。

**Comment by Tongjilibo** [comment]
是的，需要按照你这样修改
