### ISSUE TITLE
task_relation_extraction_SPN4RE.py运行问题

### ISSUE THREAD

**Issue by lili-li-cpu** [Tongjilibo/bert4torch#90]
![1}@OFXK`H%WESXST}%}R76A](https://user-images.githubusercontent.com/66951248/218957404-a1d8f165-de3e-498b-8fa4-b56377f79487.png)
用0.2版本的bert4torch,3.1.0版本的transformer运行时，出现了上面的问题

**Comment by lili-li-cpu** [comment]
所以它这个属于版本问题嘛

**Comment by Tongjilibo** [comment]
> 所以它这个属于版本问题嘛

应该是的，你可以参考我的版本来测试下看看

**Comment by lili-li-cpu** [comment]
> 

好的好的
