### ISSUE TITLE
bert4torch0.2.7版本和样例代码不兼容

### ISSUE THREAD

**Issue by wxwmaple** [Tongjilibo/bert4torch#91]
降级到bert4torch0.2.6后，代码可行

**Comment by Tongjilibo** [comment]
你好，是哪个样例不兼容，我这里修改测试一下

**Comment by Tongjilibo** [comment]
bert4torch 0.2.7是搭配torch4keras 0.0.6版本使用，烦请检测下版本然后贴一下哪些示例代码错误
