### ISSUE TITLE
task_relation_extraction_tplinker跑出来的结果P、R、F1全是0

### ISSUE THREAD

**Issue by 1365717822** [Tongjilibo/bert4torch#93]
大佬好，如题代码没有改过，跑的百度2019数据集，您有空的时候可以看一下么？非常感谢。

**Comment by Tongjilibo** [comment]
你是跑了一个epoch吗

**Comment by 1365717822** [comment]
跑了100个epoch了还是一样，tplinker_plus就没问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月17日(星期五) 中午11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tongjilibo/bert4torch] task_relation_extraction_tplinker跑出来的结果P、R、F1全是0 (Issue #93)





 
你是跑了一个epoch吗

**Comment by Tongjilibo** [comment]
好的，我查一下

**Comment by Tongjilibo** [comment]
![image](https://user-images.githubusercontent.com/33407736/220798133-a6113805-e7fa-4464-abe0-7525eaf3777a.png)
这是我跑的tplinker关系提取第10个epoch的指标，不过我测试下来指标并不高，欢迎反馈~

**Comment by 1365717822** [comment]
好的，我再试试，感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 上午8:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tongjilibo/bert4torch] task_relation_extraction_tplinker跑出来的结果P、R、F1全是0 (Issue #93)





 

 这是我跑的tplinker关系提取第10个epoch的指标，不过我测试下来指标并不高，欢迎反馈~
