### ISSUE TITLE
有关自己工程相关的语料

### ISSUE THREAD

**Issue by leizhu1989** [Tongjilibo/bert4torch#96]
作者，您好！感谢您的共享与开源
有个问题想请教下，现在我有不多的自己的中文语料数据(跟自己业务有关)，可以通过这个工程想学习下自己的数据，在用这个模型做句子相似度的计算，请问这样要关注您这个项目里面哪些部分的内容呢，看到pretrain里面还用到了simBert，而要直接训练两个句子的相似度，又缺乏跟他类似的标注。

**Comment by Tongjilibo** [comment]
如果你的数据中没有监督语料，感觉只能用无监督的句子相似度，可以参考https://github.com/Tongjilibo/bert4torch/tree/master/examples/sentence_embedding中无监督的部分，我的理解可能训练只能用无监督的训练方式比如simcse这类，其次你可以直接调用开源的句子相似度模型，看看在你的语料上的表现

**Comment by leizhu1989** [comment]
谢谢大佬提点指示，那种mlm的训练方法不太适合我这个少量的数据集吗，mlm的训练方式是不是就是学习我的语料啊

**Comment by Tongjilibo** [comment]
mlm预训练肯定是可以训练的，只是我理解和你想要计算句子相似度关联性不是很大，你mlm训练完了拿哪个作为句向量呢？当然实验下是更好哈~

**Comment by leizhu1989** [comment]
对啊，想通过这种方式预训练，然后根据您代码里面的计算特征向量相似度方法，这样可行吗

**Comment by Tongjilibo** [comment]
技术上肯定是没问题的，直接用mlm的模型来取句向量，效果需要实测下（有个先验知识是直接拿预训练的bert的句向量效果是一般的）

**Comment by leizhu1989** [comment]
嗯嗯，也就是说还是需要结合自己的数据集来调一个跟自己数据相关的句向量模型，这样效果好的可能性高些吧

**Comment by Tongjilibo** [comment]
你可以试试看，不过我感觉mlm做句向量的效果可能未必能好，如果有好的效果，期待你的反馈哈

**Comment by leizhu1989** [comment]
好的，我试了肯定跟大佬说，按照大佬的思路，我找了个别人训练的模型，就在#82这个问题里兄弟找的模型，感觉对自己的语料还不错啊，想先试试看

**Comment by leizhu1989** [comment]
大佬，我调试您的代码，发现有个奇怪的问题；我找了#82提到的模型跑的basic_language_model_simbert.py，如果我将_, Z = model.predict([X, S])改成_, Z = model(X, S)发现pooler输出不同，但输入token_ids是相同的，发现第一种方式模型进入Trainer里面，第二个直接使用Model类的forward，请问这两个有什么区别吗。看Trainer里面的走向似乎没发现什么差别啊，可是结果不同。第一种方式的效果比较好

**Comment by Tongjilibo** [comment]
你直接model(X,S)应该需要设置eval模式，且@torch.no_grad()一下吧，否则你是训练阶段的forward过程，你试一下是不是

**Comment by leizhu1989** [comment]
好的，谢谢作者，就是没加eval导致的，还有请问这个转onnx想用tensorrt加速的话有参考的吗，感觉数据预处理那部分不是在模型里面吧，模型里面需要包含哪些啊

**Comment by Tongjilibo** [comment]
我有提供示例，可以参考https://github.com/Tongjilibo/bert4torch/tree/master/examples/serving/triton，具体遇到问题可以再提issue，这个issue我close了，尽量一个issue讨论一个话题
