### ISSUE TITLE
albert_unshared

### ISSUE THREAD

**Issue by skykiseki** [Tongjilibo/bert4torch#97]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:   ubuntu 20.04
- 你使用的**Python**版本:  3.8.10
- 你使用的**Pytorch**版本:  1.10.2
- 你使用的**bert4torch**版本:  0.2.7
- 你加载的**预训练模型**: albert_base

### 核心代码
```python
# 请在此处贴上你的核心代码

model = build_tranformer_model(config_path, checkpoint_path, model='albert_unshared')

```

### 输出信息
```shell
# 请在此处贴上你的调试输出
TypeError: super() takes no keyword arguments


```

### 自我尝试
但是model='albert'没有问题，看源码自我修改加上super(Albert_unshared, self).__init__()后，权重直接无法加载

================等等，这里是不是打错字了，warnimg -> warning
[WARNIMG] Parameter encoderLayer.7.multiHeadAttention.k.weight node loaded from pretrain models

**Comment by Tongjilibo** [comment]
是的，有bug我修复了下，应该是`super(ALBERT_Unshared, self).__init__(*args, **kwargs)`，另外笔误也修改了下，谢谢~

**Comment by skykiseki** [comment]
> 是的，有bug我修复了下，应该是`super(ALBERT_Unshared, self).__init__(*args, **kwargs)`，另外笔误也修改了下，谢谢~

但是我加入了,self后其实权重是无法加载的，这个地方我就暂时不知道怎么处了，只能祈祷跪求波神有空改改了

**Comment by Tongjilibo** [comment]
好的，我看一下
