### ISSUE TITLE
seq2seq/task_seq2seq_simbert.py  里面用到的数据集data_similarity.json

### ISSUE THREAD

**Issue by Liekkas22years** [Tongjilibo/bert4torch#98]
seq2seq/task_seq2seq_simbert.py  里面用到的数据集data_similarity.json，我在readme文件中examples数据集的链接中找不到，我看代码里它的路径是位于../datasets/data_similarity.json

**Comment by Tongjilibo** [comment]
您好，这个数据也只是示例数据，[百度云链接](https://pan.baidu.com/s/1jnGNGYw9VGzmGpEf8po-mQ?pwd=nzr2)

**Comment by Liekkas22years** [comment]
谢谢您
